### ISSUE TITLE
saved parameter of patch aren't reflected in the UI of amsynth VST on reload

### ISSUE THREAD

**Issue by genlog** [amsynth/amsynth#10]
Hi Nick,

I said on linuxmusicians(tripomatic) that the vst was running fine in Bitwig, but i noticed now that there are problems. The patch is being saved fine. If I a reopen bitwig/project/UI the parameters don't show up in the UI however the patch sounds like it's saved. 

Look like the UI isn't picking up the save parameters? This is in Bitwig 1.3 and 1.2 also. 

little screencast for the issue: 
http://users.telenet.be/tripomatic/amsynth_vst_bitwig.mp4

Greetings,
Stijn

**Comment by nixxcode** [comment]
Thanks for reporting this.

It should now be fixed (by commit 321ff5e)

**Comment by genlog** [comment]
Just build the git version. Works like it should now. Close, re-open the UI, project etc. The parameters are shown like it should.

Great & Fast work!
