### ISSUE TITLE
FreeBSD / TrueOS support

### ISSUE THREAD

**Issue by danboid** [amsynth/amsynth#100]
### Expected behavior

Build and run under FreeBSD / TrueOS. Well, it'd be nice! ;)

I have been running TrueOS as my main OS for the last few weeks and I'm liking it a lot. I wanted to switch from Linux so I get fully supported ZFS with all its great benefits (mainly boot environments and snapshots) plus, and more relevant for amsynth, I greatly prefer OSS (the default soundsystem in FreeBSD and TrueOS) to ALSA. It's so much easier to manage and you can easily run JACK alongside PA or other OSS apps. I hear the FreeBSD kernel is more RT safe than Linux is, by default (without special RT patches) at least. It 'just works' more than Linux for me, most notably for audio.

### Actual behavior

 CXX      src/GUI/amsynth-editor_menus.o
src/GUI/editor_menus.cpp:200:13: warning: format string is not a string literal (potentially insecure) [-Wformat-security]
            message);
            ^~~~~~~
src/GUI/editor_menus.cpp:200:13: note: treat the string as an argument to avoid this
            message);
            ^
            "%s", 
src/GUI/editor_menus.cpp:201:74: warning: format string is not a string literal (potentially insecure) [-Wformat-security]
    gtk_message_dialog_format_secondary_text(GTK_MESSAGE_DIALOG(dialog), secondary);
                                                                         ^~~~~~~~~
src/GUI/editor_menus.cpp:201:74: note: treat the string as an argument to avoid this
    gtk_message_dialog_format_secondary_text(GTK_MESSAGE_DIALOG(dialog), secondary);
                                                                         ^
                                                                         "%s", 
2 warnings generated.
  CC       src/GUI/amsynth-editor_pane.o
  CXX      src/GUI/amsynth-ConfigDialog.o
  CXX      src/GUI/amsynth-gui_main.o
  CXX      src/GUI/amsynth-MainMenu.o
src/GUI/MainMenu.cpp:162:17: warning: 'getPresetController' is deprecated [-Wdeprecated-declarations]
                        synthesizer->getPresetController()->savePresets(config.current_bank_file.c_str());
                                     ^
src/GUI/../Synthesizer.h:92:23: note: 'getPresetController' has been explicitly marked deprecated here
    PresetController *getPresetController() DEPRECATED { return _presetController; }
                      ^
src/GUI/MainMenu.cpp:164:17: warning: 'getPresetController' is deprecated [-Wdeprecated-declarations]
                        synthesizer->getPresetController()->loadPresets(config.current_bank_file.c_str());
                                     ^
src/GUI/../Synthesizer.h:92:23: note: 'getPresetController' has been explicitly marked deprecated here
    PresetController *getPresetController() DEPRECATED { return _presetController; }
                      ^
src/GUI/MainMenu.cpp:184:17: warning: 'getPresetController' is deprecated [-Wdeprecated-declarations]
                        synthesizer->getPresetController()->savePresets(filename);
                                     ^
src/GUI/../Synthesizer.h:92:23: note: 'getPresetController' has been explicitly marked deprecated here
    PresetController *getPresetController() DEPRECATED { return _presetController; }
                      ^
src/GUI/MainMenu.cpp:185:17: warning: 'getPresetController' is deprecated [-Wdeprecated-declarations]
                        synthesizer->getPresetController()->notify();
                                     ^
src/GUI/../Synthesizer.h:92:23: note: 'getPresetController' has been explicitly marked deprecated here
    PresetController *getPresetController() DEPRECATED { return _presetController; }
                      ^
src/GUI/MainMenu.cpp:284:41: warning: 'getPresetController' is deprecated [-Wdeprecated-declarations]
                std::string presetData = synthesizer->getPresetController()->getCurrentPreset().toString();
                                                      ^
src/GUI/../Synthesizer.h:92:23: note: 'getPresetController' has been explicitly marked deprecated here
    PresetController *getPresetController() DEPRECATED { return _presetController; }
                      ^
src/GUI/MainMenu.cpp:296:53: warning: 'getPresetController' is deprecated [-Wdeprecated-declarations]
                PresetController *presetController = synthesizer->getPresetController();
                                                                  ^
src/GUI/../Synthesizer.h:92:23: note: 'getPresetController' has been explicitly marked deprecated here
    PresetController *getPresetController() DEPRECATED { return _presetController; }
                      ^
src/GUI/MainMenu.cpp:326:53: warning: 'getPresetController' is deprecated [-Wdeprecated-declarations]
                gtk_entry_set_text(GTK_ENTRY(entry), synthesizer->getPresetController()->getCurrentPreset().getName().c_str());
                                                                  ^
src/GUI/../Synthesizer.h:92:23: note: 'getPresetController' has been explicitly marked deprecated here
    PresetController *getPresetController() DEPRECATED { return _presetController; }
                      ^
src/GUI/MainMenu.cpp:335:17: warning: 'getPresetController' is deprecated [-Wdeprecated-declarations]
                        synthesizer->getPresetController()->getCurrentPreset().setName(text);
                                     ^
src/GUI/../Synthesizer.h:92:23: note: 'getPresetController' has been explicitly marked deprecated here
    PresetController *getPresetController() DEPRECATED { return _presetController; }
                      ^
src/GUI/MainMenu.cpp:336:17: warning: 'getPresetController' is deprecated [-Wdeprecated-declarations]
                        synthesizer->getPresetController()->notify();
                                     ^
src/GUI/../Synthesizer.h:92:23: note: 'getPresetController' has been explicitly marked deprecated here
    PresetController *getPresetController() DEPRECATED { return _presetController; }
                      ^
src/GUI/MainMenu.cpp:357:17: warning: 'getPresetController' is deprecated [-Wdeprecated-declarations]
                        synthesizer->getPresetController()->clearPreset();
                                     ^
src/GUI/../Synthesizer.h:92:23: note: 'getPresetController' has been explicitly marked deprecated here
    PresetController *getPresetController() DEPRECATED { return _presetController; }
                      ^
src/GUI/MainMenu.cpp:365:16: warning: 'getPresetController' is deprecated [-Wdeprecated-declarations]
                synthesizer->getPresetController()->randomiseCurrentPreset();
                             ^
src/GUI/../Synthesizer.h:92:23: note: 'getPresetController' has been explicitly marked deprecated here
    PresetController *getPresetController() DEPRECATED { return _presetController; }
                      ^
src/GUI/MainMenu.cpp:370:16: warning: 'getPresetController' is deprecated [-Wdeprecated-declarations]
                synthesizer->getPresetController()->undoChange();
                             ^
src/GUI/../Synthesizer.h:92:23: note: 'getPresetController' has been explicitly marked deprecated here
    PresetController *getPresetController() DEPRECATED { return _presetController; }
                      ^
src/GUI/MainMenu.cpp:375:16: warning: 'getPresetController' is deprecated [-Wdeprecated-declarations]
                synthesizer->getPresetController()->redoChange();
                             ^
src/GUI/../Synthesizer.h:92:23: note: 'getPresetController' has been explicitly marked deprecated here
    PresetController *getPresetController() DEPRECATED { return _presetController; }
                      ^
src/GUI/MainMenu.cpp:382:17: warning: 'getPresetController' is deprecated [-Wdeprecated-declarations]
                        synthesizer->getPresetController()->importPreset(filename);
                                     ^
src/GUI/../Synthesizer.h:92:23: note: 'getPresetController' has been explicitly marked deprecated here
    PresetController *getPresetController() DEPRECATED { return _presetController; }
                      ^
src/GUI/MainMenu.cpp:388:39: warning: 'getPresetController' is deprecated [-Wdeprecated-declarations]
                std::string filename = synthesizer->getPresetController()->getCurrentPreset().getName() + ".amSynthPreset";
                                                    ^
src/GUI/../Synthesizer.h:92:23: note: 'getPresetController' has been explicitly marked deprecated here
    PresetController *getPresetController() DEPRECATED { return _presetController; }
                      ^
src/GUI/MainMenu.cpp:391:17: warning: 'getPresetController' is deprecated [-Wdeprecated-declarations]
                        synthesizer->getPresetController()->exportPreset(filename);
                                     ^
src/GUI/../Synthesizer.h:92:23: note: 'getPresetController' has been explicitly marked deprecated here
    PresetController *getPresetController() DEPRECATED { return _presetController; }
                      ^
src/GUI/MainMenu.cpp:406:42: warning: 'getMidiController' is deprecated [-Wdeprecated-declarations]
                        const int currentValue = synthesizer->getMidiController()->get_midi_channel();
                                                              ^
src/GUI/../Synthesizer.h:91:21: note: 'getMidiController' has been explicitly marked deprecated here
    MidiController *getMidiController() DEPRECATED { return _midiController; };
                    ^
src/GUI/MainMenu.cpp:469:35: warning: 'getMidiController' is deprecated [-Wdeprecated-declarations]
                int currentValue = synthesizer->getMidiController()->get_midi_channel();
                                                ^
src/GUI/../Synthesizer.h:91:21: note: 'getMidiController' has been explicitly marked deprecated here
    MidiController *getMidiController() DEPRECATED { return _midiController; };
                    ^
src/GUI/MainMenu.cpp:471:17: warning: 'getMidiController' is deprecated [-Wdeprecated-declarations]
                        synthesizer->getMidiController()->set_midi_channel(newValue);
                                     ^
src/GUI/../Synthesizer.h:91:21: note: 'getMidiController' has been explicitly marked deprecated here
    MidiController *getMidiController() DEPRECATED { return _midiController; };
                    ^
19 warnings generated.
  CXX      src/GUI/amsynth-MainWindow.o
src/GUI/MainWindow.cpp:50:34: warning: 'getPresetController' is deprecated [-Wdeprecated-declarations]
                        presetController(synthesizer->getPresetController())
                                                      ^
src/GUI/../Synthesizer.h:92:23: note: 'getPresetController' has been explicitly marked deprecated here
    PresetController *getPresetController() DEPRECATED { return _presetController; }
                      ^
src/GUI/MainWindow.cpp:291:17: warning: 'getMidiController' is deprecated [-Wdeprecated-declarations]
                        synthesizer->getMidiController(),
                                     ^
src/GUI/../Synthesizer.h:91:21: note: 'getMidiController' has been explicitly marked deprecated here
    MidiController *getMidiController() DEPRECATED { return _midiController; };
                    ^
src/GUI/MainWindow.cpp:292:17: warning: 'getPresetController' is deprecated [-Wdeprecated-declarations]
                        synthesizer->getPresetController(),
                                     ^
src/GUI/../Synthesizer.h:92:23: note: 'getPresetController' has been explicitly marked deprecated here
    PresetController *getPresetController() DEPRECATED { return _presetController; }
                      ^
3 warnings generated.
  CXX      src/GUI/amsynth-MIDILearnDialog.o
  CXX      src/GUI/amsynth-PresetControllerView.o
  CXXLD    amsynth
make[2]: don't know how to make data/amsynth.appdata.xml. Stop

make[2]: stopped in /usr/home/dan/src/amsynth-1.8.0
*** Error code 1

Stop.
make[1]: stopped in /usr/home/dan/src/amsynth-1.8.0
*** Error code 1

Stop.
make: stopped in /usr/home/dan/src/amsynth-1.8.0

### Information

  - Which version of amsynth are you using?

1.8.0

  - Which build of amsynth are you using? (stand-alone application, LV2, DSSI, VST)

I'm only really bothered about LV2 (and/or VST)

  - If using amsynth as a plugin, which host application are you using?

I'll be testing under Ardour

  - Which operating system & version are you using?

Latest TrueOS

### Steps to reproduce the behavior

  1. ... ./configure
  2. ... make

**Comment by danboid** [comment]
'scuse me!

I must look before I post bug reports! Amsynth did build it seems, just a docs issue it seems?

make install wasn't entirely happy either:

make install
Making install in po
linguas="";  for lang in $linguas; do  dir=/usr/local/share/locale/$lang/LC_MESSAGES;  /bin/sh /usr/home/dan/src/amsynth-1.8.0/install-sh -d $dir;  if test -r $lang.gmo; then  /usr/bin/install -c -m 644 $lang.gmo $dir/amsynth.mo;  echo "installing $lang.gmo as $dir/amsynth.mo";  else  /usr/bin/install -c -m 644 ./$lang.gmo $dir/amsynth.mo;  echo "installing ./$lang.gmo as"  "$dir/amsynth.mo";  fi;  if test -r $lang.gmo.m; then  /usr/bin/install -c -m 644 $lang.gmo.m $dir/amsynth.mo.m;  echo "installing $lang.gmo.m as $dir/amsynth.mo.m";  else  if test -r ./$lang.gmo.m ; then  /usr/bin/install -c -m 644 ./$lang.gmo.m  $dir/amsynth.mo.m;  echo "installing ./$lang.gmo.m as"  "$dir/amsynth.mo.m";  else  true;  fi;  fi;  done
make[1]: don't know how to make data/amsynth.appdata.xml. Stop

make[1]: stopped in /usr/home/dan/src/amsynth-1.8.0
*** Error code 1

Stop.
make: stopped in /usr/home/dan/src/amsynth-1.8.0

**Comment by danboid** [comment]
I've got amsynth standalone working with my USB MIDI keyboard but there's notable latency between keypress and amsynth making a noise which I'll have to look into.

**Comment by nixxcode** [comment]
The audio latency is controlled by [OSSAudioDriver::setRealtime](https://github.com/amsynth/amsynth/blob/develop/src/drivers/OSSAudioDriver.cc#L149) - but it's been a long time since I've used the OSS audio layer so it might need some work.

**Comment by danboid** [comment]
Hi Nick

Sorry, I was too tired to be trying stuff out for the first time last night, so I should've waited to post any bug reports!

I've got the latency prob sorted - I didn't have:

kern.timecounter.alloweddeviation=0
hw.usb.uaudio.buffer_ms=2 # only on -STABLE for now
hw.snd.latency=0

In my /etc/sysctl.conf - I think its that first line that is relevant here.

That was testing with a half-working amsynth - as t stands I don't have a full GUI as its not installing the skins properly.

clang gives a few warnings when trying to build it and then ultimately gives up with the error:

make[2]: don't know how to make data/amsynth.appdata.xml. Stop

Why is make looking for data/amsynth.appdata.xml. when the file is actually called data/amsynth.appdata.xml.in - thats what it says in the Makefile.

Here's the full configure and build output under TrueOS:

https://gist.github.com/danboid/c1e00f0df477f56cfddf167448a05a32

**Comment by nixxcode** [comment]
`amsynth.appdata.xml` is created by processing `amsynth.appdata.xml.in` - this appears to be done by `@INTLTOOL_XML_RULE@` in [Makefile.am](/amsynth/amsynth/blob/develop/Makefile.am#L294)

Maybe `INTLTOOL_XML_RULE` is not defined on your system; it should be defined in `aclocal.m4`

Are you building from a Git checkout or the release tarball?

**Comment by danboid** [comment]
Hi Nick

I have tried both the latest release tarball and I've just tried the latest git and the both have the same prob.

As for that string:

dan@true76:~/src/amsynth % grep INTLTOOL_XML_RULE *
aclocal.m4:      INTLTOOL_XML_RULE='%.xml:       %.xml.in       $(INTLTOOL_MERGE) $(wildcard $(top_srcdir)/po/*.po) ; $(INTLTOOL_V_MERGE)LC_ALL=C $(INTLTOOL_MERGE) $(INTLTOOL_V_MERGE_OPTIONS) -x -u -c $(top_builddir)/po/.intltool-merge-cache $(top_srcdir)/po $< [$]@' 
aclocal.m4:_IT_SUBST(INTLTOOL_XML_RULE)
config.log:INTLTOOL_XML_RULE='%.xml:       %.xml.in       $(INTLTOOL_MERGE) $(wildcard $(top_srcdir)/po/*.po) ; $(INTLTOOL_V_MERGE)LC_ALL=C $(INTLTOOL_MERGE) $(INTLTOOL_V_MERGE_OPTIONS) -x -u -c $(top_builddir)/po/.intltool-merge-cache $(top_srcdir)/po $< $@'
config.status:S["INTLTOOL_XML_RULE"]="%.xml:       %.xml.in       $(INTLTOOL_MERGE) $(wildcard $(top_srcdir)/po/*.po) ; $(INTLTOOL_V_MERGE)LC_ALL=C $(INTLTOOL_MERGE) $(INTLTOOL_V_MERGE_O"\
configure:INTLTOOL_XML_RULE
configure:      INTLTOOL_XML_RULE='%.xml:       %.xml.in       $(INTLTOOL_MERGE) $(wildcard $(top_srcdir)/po/*.po) ; $(INTLTOOL_V_MERGE)LC_ALL=C $(INTLTOOL_MERGE) $(INTLTOOL_V_MERGE_OPTIONS) -x -u -c $(top_builddir)/po/.intltool-merge-cache $(top_srcdir)/po $< $@'
Makefile.am:@INTLTOOL_XML_RULE@
Makefile.in:@INTLTOOL_XML_RULE@

**Comment by nixxcode** [comment]
Looks like it is defined properly, then.

What do you see when you run `make V=1 data/amsynth.appdata.xml` ? I get the following:
```
$ make V=1 data/amsynth.appdata.xml 
LC_ALL=C /usr/bin/intltool-merge  -x -u -c ./po/.intltool-merge-cache ./po data/amsynth.appdata.xml.in data/amsynth.appdata.xml
Generating and caching the translation database
Merging translations into data/amsynth.appdata.xml.
CREATED data/amsynth.appdata.xml
```

**Comment by nixxcode** [comment]
@danboid I have a solution for you! Install `gmake` (GNU make) and use that instead of the normal `make` command. Worked for me on a TrueOS system.

**Comment by danboid** [comment]
Thanks Nick

I'm surprised I didn't try that first but I always thought the configure script would work out which make to use and let me  run `make` without thinking? Maybe not.

The GUI works in amsynth standalone now bu I can't get the LV2 GUI to open under Ardour, it just says

[ERROR]: failed to instantiate LV2 GUI

Every time I try to open the LV2 GUI. using Ardour 5.8.0 from the TrueOS repos.

**Comment by danboid** [comment]
I did a git pull, noticed there had been changes so I dd a make clean and rebuilt amsynth and now the LV2GUI is working under Ardour.

I expect what I did before was I did half a build with BSD make then finished it with gmake so it was a bit of a hybrid.

**Comment by nickdowell** [comment]
amsynth's GUI has been rebuilt with JUCE and I'd love to hear from anyone using amsynth on BSDs and know if it still builds & works there 🙏
