### ISSUE TITLE
Question - how to select patch via midi controller ?

### ISSUE THREAD

**Issue by VinceLewis** [amsynth/amsynth#102]
I learned how to map controllers to the software knobs (env, filter, drive, etc)
However, I can't seem to map my controller to change the patch. Can you tell me how please? I plan on using amsynth with a laptop for live use.

### Information

  - Which version of amsynth are you using?
amsynth 1.5.1

  - Which build of amsynth are you using? (stand-alone application, LV2, DSSI, VST)
Stand alone

  - If using amsynth as a plugin, which host application are you using?
n/a

  - Which operating system & version are you using?
Ubuntu Studio 14.04

**Comment by nixxcode** [comment]
amsynth does not support changing patch via a MIDI CC because there is a dedicated MIDI message for changing patch (and bank) which amsynth supports. Hopefully your controller can send these

**Comment by VinceLewis** [comment]
Many thanks, closing the issue
