### ISSUE TITLE
Question - how to set midi channel via command line

### ISSUE THREAD

**Issue by VinceLewis** [amsynth/amsynth#103]
How can I set the midi channel on startup ?
I would like to run 2 (or more) instances of amsynth in gui-less mode, for live use.

### Information

  - Which version of amsynth are you using?
1.5.1

  - Which build of amsynth are you using? (stand-alone application, LV2, DSSI, VST)
stand alone
  - If using amsynth as a plugin, which host application are you using?
n/a

  - Which operating system & version are you using?
ubuntu studio 14.04

**Comment by nixxcode** [comment]
Using the '-c' option; e.g. 'amsynth -c 2' will tell amsynth to listen on MIDI channel 2

**Comment by VinceLewis** [comment]
Many thanks, closing the ticket.
