### ISSUE TITLE
Add parameter to limit voices / polyphony

### ISSUE THREAD

**Issue by kjyv** [amsynth/amsynth#106]
In case I haven't overlooked it: It would be very useful to have a parameter to set a maximum number of voices (older ones being removed) for playing live with amsynth. Currently with e.g. longer sustain values I sometimes have too high cpu usage and get dropouts (happens more quickly on a raspberry pi). 

### Information

  - Which version of amsynth are you using?
amsynth 1.8.0
  - Which build of amsynth are you using? (stand-alone application, LV2, DSSI, VST)
LV2
  - If using amsynth as a plugin, which host application are you using?
mod-host
  - Which operating system & version are you using?
raspbian jessie

### Steps to reproduce the behavior

  1. increase the amp_sustain
  2. play a few chords

**Comment by nixxcode** [comment]
There is no MIDI control or UI on the plus-ins to configure the polyphony. However, if you launch the stand-alone GUI and select a value, it will be saved to `~/.amSynthrc` and read by the plug-ins. 

If you cannot launch the stand-alone GUI, edit `~/.amSynthrc` manually, for example;
```
polyphony   10
```

**Comment by kjyv** [comment]
Ok thanks, that will do for me.
