### ISSUE TITLE
Crackling when parameters are changed

### ISSUE THREAD

**Issue by kjyv** [amsynth/amsynth#107]
When changing e.g. the volume, there should not be any extra noise. Other parameters such as reverb_roomsize exhibit the same behavior. I don't get the same issues in the standalone version or with other lv2 plugins on the same host.

### Information

  - Which version of amsynth are you using?
1.8.0
  - Which build of amsynth are you using? (stand-alone application, LV2, DSSI, VST)
LV2
  - If using amsynth as a plugin, which host application are you using?
mod-host
  - Which operating system & version are you using?
raspbian jessie

### Steps to reproduce the behavior

  1. load amsynth lv2 plugin in mod-host (or other hosts possibly)
  2. map a knob to master_vol
  3. play some notes and change volume -> should produce some noisy dirt

**Comment by kjyv** [comment]
This changed a bit for me (after reinstalling a newer debian system). I no longer get noise from the volume parameter but I get the crackling if I turn midi cc #7 even if I don't map it to an lv2 parameter through mod-host. The CC midi input should be ignored if running as lv2 plugin I guess?

**Comment by kjyv** [comment]
Testing this a bit more, I noticed it also happens in standalone mode when changing the volume with the mouse or midi cc. Other parameters are reverb wet, lfo to amp or amp env sustain.
@nickdowell I don't really have an idea where to start looking but in case you have a hunch where this could be coming from, I'd dig into it.

**Comment by kjyv** [comment]
Regarding my previous comment: amsynth running as lv2 plugin apparently still uses the midi mappings that were set when running standalone. That is a separate bug though.

**Comment by kjyv** [comment]
![bildschirmfoto vom 2018-01-24 13-50-40](https://user-images.githubusercontent.com/12260/35333060-99e3beee-010d-11e8-8045-6da1cbf373e1.png)
Looks like parameter smoothing could help?

**Comment by nickdowell** [comment]
@kjyv thanks for the feedback, which parameters did you find needed smoothing?

**Comment by kjyv** [comment]
Well, for a start, master volume, but there are some more as written above (reverb wet, lfo to amp, amp env sustain). Probably everything that results in these jumps in the signal. I don't have a complete list yet. The effects are more audible when using higher buffer sizes (which makes sense) set with jack in case you're having trouble trying it for yourself.

**Comment by grantsmith1969** [comment]
Can confirm that master volume midi events cause a LOT of crackling in amsynth for me.

**Comment by nickdowell** [comment]
Parameter smoothing has been added in release 1.10.0

**Comment by kjyv** [comment]
Nice, thanks
