### ISSUE TITLE
Modify default tuning at startup

### ISSUE THREAD

**Issue by nobrakal** [amsynth/amsynth#11]
Hi,

I run amsynth on rapsberry pi, in headless mode, and I want to load a tuning file at startup. I think is a good idea to add this in a command line option, and, better, to allow the user to change the tuning with midi signal.

For now, I have modified a little bit amsynth sources to load a tuning file at startup from .Amsynthrc, with a line called tuning_file (you can see the sources here: https://github.com/nobrakal/amsynth). It's not really beautiful since I'm not a c programmer, but it's work.

**Comment by nixxcode** [comment]
Thanks, I've merged in your changes and fixed some build issues - 5a84128  - and fixed command line option handling - 034c870

Let me know if it works for you so I can close this ticket :)

**Comment by nobrakal** [comment]
This works very well, thank you for your help :D
