### ISSUE TITLE
Can't build amsynth 1.8.0 on 32-bit

### ISSUE THREAD

**Issue by VinceLewis** [amsynth/amsynth#110]
### Expected behavior
trying to make amsynth 1.8.0 in debian 32 bit system. 

### Actual behavior
fails with message:
/usr/bin/ld: i386:x86-64 architecture of input file src/amsynth-lash.o is incompatible with i386 output
....
makefile:1732 : recipe for target amsynth failed

### Information
 (note I did successfully build on ubuntu 64bit)

  - Which version of amsynth are you using?1.8.0
  - Which build of amsynth are you using? (stand-alone application, LV2, DSSI, VST) stand alone
  - If using amsynth as a plugin, which host application are you using?
  - Which operating system & version are you using? debian 9

### Steps to reproduce the behavior

  1. ... ./configure --without-lv2 --without-jack --without-dssi --without-vst

  2. ... make

**Comment by nickdowell** [comment]
I cannot reproduce this build error on a fresh install of debian 9 i386

Please attach your `config.log` and output of running `make V=1` for further diagnostic info

**Comment by VinceLewis** [comment]
attached. I'm going to try again with a fresh install of debian 9. Note I do an absolute minimal install, as I only have a 2GB drive. I then have to install lots of things to be able to build it....

The specific purpose of me doing this setup is to have the 1.8.0 version there to be able to do 2-way comms with my midi controller. I know I can do "dump to midi" option in 1.6.4, but I really would like the auto-write that 1.8.0 gives to avoid having to do that "dump" option on all 6 planned amsynth instances

[config.log](https://github.com/amsynth/amsynth/files/1504217/config.log)
[makelog.log](https://github.com/amsynth/amsynth/files/1504218/makelog.log)

**Comment by VinceLewis** [comment]
I have resolved this issue. It was caused by me unzipping the release TAR on a 64bit machine, doing the autogen etc and making it fine, then copying THAT version of the directory to the 32 bit machine.
When I copied the original TAR to the 32 bit machine and unzipped, it worked fine.
Humble apologies

**Comment by trebmuh** [comment]
Thanks for sharing the resolution.
