### ISSUE TITLE
[Question] error opening 

### ISSUE THREAD

**Issue by teamblubee** [amsynth/amsynth#112]
I am using amsynth 1.8.0

I am using OSS driver for both midi and would also like to use OSS for the audio output driver as well but I run into a few issues.

My default midi device is /dev/umidi0.0, I set that in the amsynth configuration screen and it works as expected, playing midi keyboard the synth works.

The prefered audio driver has auto, jack, alsa-mmap, alsa, and oss.

My default audio device is /dev/dsp1.0 for speakers and /dev/dsp2.0 for headphones.

I have to leave prefered audio driver on auto with
OSS audio device set to: /dev/dsp1.0
ALSA audio device set to default

when I launch amsynth from the command line I see the message:
```shell
blubee:~ % amsynth
connect(2) call to /tmp/jack-1001/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
```
testing out from the command line amsynth -a oss, there's no audio at all.
running ossinfo i get these output
```shell
blubee:~ % ossinfo
Version info: FreeBSD native OSS ABI 1200054 (0x00040000) BSD
Platform: FreeBSD/amd64 12.0-CURRENT FreeBSD 12.0-CURRENT #0 r326056: Tue Nov 21 14:54:55 UTC 2017     root@releng3.nyi.freebsd.org:/usr/obj/usr/src/amd64.amd64/sys/GENERIC (blubee)

Number of audio devices:	9
Number of audio engines:	9
Number of MIDI devices:		0
Number of mixer devices:	3


Device objects
 0: pcm0 Realtek ALC899 (Analog)
    on hdaa0 
 1: pcm1 Realtek ALC899 (Rear Analog Line-out)
    on hdaa0 
 2: pcm2 Realtek ALC899 (Rear Digital)
    on hdaa0 

MIDI devices (/dev/midi*)

Mixer devices
 0: pcm0:mixer (Mixer 0 of device object 0)
 1: pcm1:mixer (Mixer 0 of device object 1)
 2: pcm2:mixer (Mixer 0 of device object 2)

Audio devices
pcm0:play:dsp0.p0                 /dev/dsp0.p0  (device index 0)
pcm0:virtual:dsp0.vp0             /dev/dsp0.vp0  (device index 1)
pcm0:virtual:dsp0.vp1             /dev/dsp0.vp1  (device index 2)
pcm0:record:dsp0.r0               /dev/dsp0.r0  (device index 3)
pcm0:virtual:dsp0.vr0             /dev/dsp0.vr0  (device index 4)
pcm1:play:dsp1.p0                 /dev/dsp1.p0  (device index 5)
pcm1:virtual:dsp1.vp0             /dev/dsp1.vp0  (device index 6)
pcm2:play:dsp2.p0                 /dev/dsp2.p0  (device index 7)
pcm2:virtual:dsp2.vp0             /dev/dsp2.vp0  (device index 8)
```

Shouldn't I be able to get audio through OSS instead of relying on ALSA? I am getting this error:

```shell
amsynth
err: ioctl fragment: Invalid argument
```

Could sorting out that error get audio to play through OSS instead of ALSA?

I do not want to run jack, ever because once OSS is properly sorted out audio can be routed w/o running jack server.

**Comment by nickdowell** [comment]
The OSS code in amsynth probably needs some work to bring it up-to-date. It was, after all, written 16 years ago for an earlier version of the OSS API and without FreeBSD in mind!

**Comment by nickdowell** [comment]
I've made some improvements to the OSS audio code on a new branch - [`feature/freebsd-oss-audio`](https://github.com/amsynth/amsynth/tree/feature/freebsd-oss-audio)

Please try it out and see if it improves things for you!

**Comment by teamblubee** [comment]
Thank you, even though you wrote your OSS code 16 years ago it's still one of the easiest to setup for my midi keyboard so that's a plus for OSS.

I was testing and using alsa as audio out, there's static in the audio output.
switching to alsa-mmap the audio is clear as expected.

I'll take a look at the OSS branch you have setup.

**Comment by nickdowell** [comment]
Please re-open this issue if OSS audio is not working. I tested the latest code on FreeBSD 11 and it worked for me.
