### ISSUE TITLE
add osc detune to amsynth 

### ISSUE THREAD

**Issue by Reaper10** [amsynth/amsynth#114]
Add a  osc detune amsynth  for both osc 1/2. The knob should have a switch for switching between the semitone / octave  the detune options for the detune knob. It would all so be nice to have a detune  amount readout box  for both osc 1/2.

**Comment by nickdowell** [comment]
There are already detune controls (octave, semitone and fine) for oscillator 2. A readout is shown while the mouse is clicked on these controls.

I don't have any plans to add these same controls to oscillator 1 and don't see what new sound capabilities this would open up...?

**Comment by nickdowell** [comment]
Feel free to reopen this ticket if you have further comments, but I don't see the need for a detune control on OSC 1
