### ISSUE TITLE
bad status (254) from client amsynth while handling a xrun event

### ISSUE THREAD

**Issue by georgkrause** [amsynth/amsynth#115]
I am running jack and amsynth on an raspberry pi 3. i get the above error sometimes, actually i dont know exactly where it come from.

### Expected behavior
i press 14 or 15 keys, there should be 14/15 voices 
### Actual behavior
instead i get a hell of a lot xruns and this message:
'''
bad status (254) from client amsynth while handling a xrun event
'''
### Information

  - Which version of amsynth are you using?
amsynth 1.8.0
  - Which build of amsynth are you using? (stand-alone application, LV2, DSSI, VST)
stand-alone
  - If using amsynth as a plugin, which host application are you using?
none
  - Which operating system & version are you using?
Linux raspberrypi 4.9.70-v7+ #1068 SMP Mon Dec 18 22:12:55 GMT 2017 armv7l GNU/Linux

### Steps to reproduce the behavior

  1. Start jack: ´/usr/bin/jackd -dalsa -r48000 -p512 -n2 -Xseq -D -Chw:USB -Phw:USB > jack.log &`
  2. Start amsynth: ´amsynth -x &´
  3. Press a lot of keys

**Comment by nickdowell** [comment]
I cannot reproduce the `bad status (254)` error message when running too many voices - instead I see jackd reporting:
```
subgraph starting at amsynth timed out ...
```

or sometimes:
```
internal poll failure reading response from client amsynth to a xrun event
```

Not much we can do to address these as the logic is down in `libjack` and `jackd`

### Max. Polyphony

It sounds like the Raspberry Pi 3's CPU is not powerful enough to run 14 or 15 voices in amsynth.

My desktop PC, with its reasonably fast 4GHz Intel Core i7-6700K, starts getting xruns when running 28 voices in amsynth, so I'm not surprised that the Pi cannot handle 14.

Being single-threaded, amsynth cannot take advantage of the Pi's multiple cores - although running multiple instances of amsynth may offer a way around this.

I suggest experimenting with the `polyphony` setting in `~/.amSynthrc` to find a maximum voice count that works for you (the default value is `0` which means no limit.)

**Comment by georgkrause** [comment]
In fact i cannot reproduce this Error anymore on my own. Its pretty weird, everytime i restart the Pi it has another maximum.

Anyway, thanks for the hint, it seems like this is the reason for the crash.

Is multithreading currently on the roadmap? Amsynth is really a great synth and probably the only one which is useful for running on a raspberry pi, but currently its difficult since it uses just one core :(

**Comment by nickdowell** [comment]
Are you building amsynth from source?

If so, it's worth checking what `CFLAGS` are being used (run `make V=1` to see all the details) and trying different optimisation flags.

A reasonable starting point is
```
./configure CFLAGS='-O2 -fomit-frame-pointer'
```

**Comment by georgkrause** [comment]
Currently i am not building amsynth from source but using the version out of the raspbian repositories. I dont know how to get these information, but maybe its a good idea to just try to build it myself. Thanks for the hints, again!

But there is still the open question what your thoughts are about multi core support, is it too hard to do?

**Comment by nickdowell** [comment]
It wouldn't be too hard to build a one-off version with multi-core support, but it would be difficult to implement it in a way that would still allow building the plug-in versions etc.

Personally, I don't have a multi-core Pi so it would be tricky to test whether any changes actually improve performance there.
