### ISSUE TITLE
midi.h has midi cc bank select msb and lsb numbers reversed

### ISSUE THREAD

**Issue by msg** [amsynth/amsynth#116]
### Expected behavior

From https://www.midi.org/specifications/item/table-3-control-change-messages-data-bytes-2

CC Bank Select MSB is number 0x00 and CC Bank Select LSB is number 0x20.   In midi.h:

enum {
    MIDI_CC_BANK_SELECT_LSB             = 0x00,
    MIDI_CC_MODULATION_WHEEL            = 0x01,
        MIDI_CC_DATA_ENTRY_MSB              = 0x06,
        MIDI_CC_PAN_MSB                     = 0x0A,
    MIDI_CC_BANK_SELECT_MSB             = 0x20,
...

These numbers are opposite of the midi specification.

### Information

  - Which version of amsynth are you using? Latest github version.
  - Which build of amsynth are you using? stand-alone
  - If using amsynth as a plugin, which host application are you using?
  - Which operating system & version are you using? archlinux current

**Comment by nickdowell** [comment]
Well spotted - thanks!
