### ISSUE TITLE
Restart notes when sustain pedal is active

### ISSUE THREAD

**Issue by georgkrause** [amsynth/amsynth#118]
When i play amsynth with an active sustain pedal and send noteon for a note which is already playing, i would expect an restart, but actually nothing happens. This is kind of limiting, would be nice to if the notes could be restarted by sending noteon again.

**Comment by nickdowell** [comment]
amsynth does re-trigger a sustained note when you press the key again, except in Mono and Legato modes due to a bug - #120 

If the new note has the same volume and the volume envelope has a fully open sustain, you may not notice any change to the sound though.

**Comment by georgkrause** [comment]
Ill retest when back home

**Comment by nickdowell** [comment]
Closed due to inactivity. Please re-open if this is still an issue.
