### ISSUE TITLE
Reverb sounds wrong at sample rates above 48000

### ISSUE THREAD

**Issue by kjyv** [amsynth/amsynth#119]
### Expected behavior
Clean reverb sound

### Actual behavior
Reverb sounds like a metal bucket, saw like. Or a bit like a resonating snare drum in a loud band rehearsal.

### Information

  - Which version of amsynth are you using?
current git / 1.6.4 from ubuntu repositories
  - Which build of amsynth are you using? (stand-alone application, LV2, DSSI, VST)
LV2, standalone
  - If using amsynth as a plugin, which host application are you using?
Qtractor, any
  - Which operating system & version are you using?
Debian / Ubuntu

I've tried compiling with different optimization flags, with/without fast-math, but it does not change the sound.

**Comment by kjyv** [comment]
I've noticed that helm (https://github.com/mtytel/helm) does use pretty much the same reverb model based on freeverb but not the same code. And it sounds good, on the same box.

**Comment by legostax** [comment]
Just stumbled on this repo, and it looks like amsynth's current version is 1.8.0, and you're using version 1.6.4. Have you tried the latest version?

**Comment by kjyv** [comment]
I guess I should have written current git AND 1.6.4 instead of the /. I only mentionend this to illustrate that the issue also happens on a distribution package, not just on my specific compilation.

**Comment by nickdowell** [comment]
@kjyv what sample rate is amsynth running at?

It would be helpful if you could provide a recording of the output (preferably with one of the built-in preset sounds) that demonstrates the issue 😃

**Comment by nickdowell** [comment]
This is fixed now!

**Comment by kjyv** [comment]
Great! Haven't gotten around yet to provide you with recordings, but I'll look into it again. Cool that you found a fix, but to be honest I think I used 44100 Hz. I'll check the commit in any case.

**Comment by nickdowell** [comment]
Prior to the fix, the reverb sounded really bad at 192 kHz.

Didn't have a 192 capable card when amsynth was first developed so it had never been tested!

**Comment by kjyv** [comment]
So, sorry took me a bit to get back to this...
It's nice that you fixed a problem at higher sample rates but this is not the problem for which I created the issue. I think a simple case to reproduce this (at 44100 Hz) is to use a basic sine based preset and turn up reverb wet, reverb width and reverb roomsize all the way and then compare the reverb sound between different reverb damping values. New high frequencies are added the lower damping gets. Maybe this is the meaning of damping for this reverb algorithm but it also sounds bad  (=scratchy, distorted) with damping all the way up. Other software reverb effects don't do this.
