### ISSUE TITLE
Volume gets reset each time I change presets

### ISSUE THREAD

**Issue by thedanyes** [amsynth/amsynth#12]
Each time I change presets in amsynth, I'm forced to move my MIDI keyboard's volume lever up and then back down again in order to get amsynth to recognize my set volume level.  It would be really great if the volume level could stay constant.

**Comment by georgkrause** [comment]
there are some other controllers which may could be preset independent: drive, adsr, reverb, lfo.

**Comment by georgkrause** [comment]
this is resolved, isnt it?

**Comment by nixxcode** [comment]
@georgkrause yes, you can now right-click on any control and choose to "Ignore Preset Values" which stops it being affected by preset changes

**Comment by thedanyes** [comment]
Thank you Nick! The new feature did exactly what I wanted and it looks useful for other purposes as well.
