### ISSUE TITLE
Use of uninitialised variable

### ISSUE THREAD

**Issue by audetto** [amsynth/amsynth#122]
### Expected behavior

valgrind reports no errors

### Actual behavior

==10623== Conditional jump or move depends on uninitialised value(s)
==10623==    at 0x43E557: MainWindow::parameterDidChange(int, float) (MainWindow.cpp:256)
==10623==    by 0x43E3BB: MainWindow::UpdateParameter(Param, float) (MainWindow.cpp:224)
==10623==    by 0x40E164: Parameter::addUpdateListener(UpdateListener&) (Parameter.cc:50)
==10623==    by 0x43DC12: MainWindow::MainWindow(Synthesizer*, GenericOutput*) (MainWindow.cpp:106)
==10623==    by 0x43D4B4: main_window_new(Synthesizer*, GenericOutput*) (MainWindow.cpp:313)
==10623==    by 0x43D619: main_window_show(Synthesizer*, GenericOutput*) (MainWindow.cpp:330)
==10623==    by 0x4329F6: main (main.cc:456)

### Information

  - Which version of amsynth are you using?
1.8.0 from git
  - Which build of amsynth are you using? (stand-alone application, LV2, DSSI, VST)
standalone
  - If using amsynth as a plugin, which host application are you using?
NA
  - Which operating system & version are you using?
Linux 64 bit, Fedora 27
### Steps to reproduce the behavior

  1. Compile amsynth with "-g -O0"
  2. valgrind ./amsynth

The problem is that the member variable presetIsNotSaved (MainWindow.cpp:270) is not initialised before its usage (at MainWindow.cpp:256).

It is enough to add

presetIsNotSave = false

at line 53 at the begin of the constructor.

Andrea

**Comment by nickdowell** [comment]
This was fixed by #123
