### ISSUE TITLE
amsynth lv2 & vst export too many symbols on linux

### ISSUE THREAD

**Issue by swesterfeld** [amsynth/amsynth#125]
Someone told me that my own project, SpectMorph, exports extra symbols in the LV2 plugin, other than the lv2_decriptor symbol which it should export. Since I copied the libtool stuff from amsynth, amsynth (I tested 1.5.1) is also affected. For instance

```
$ nm -C -D /usr/lib/lv2/amsynth.lv2/amsynth_lv2.so | grep ' T '
00000000000301b4 T _fini
00000000000186d0 T get_parameter_properties
000000000000ad10 T _init
000000000000c9c0 T lv2_descriptor
0000000000013290 T parameter_get_display
0000000000012fc0 T parameter_get_value_strings
0000000000012c70 T parameter_index_from_name
0000000000019680 T parameter_name_from_index
0000000000012650 T TimeParameter(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Param)
000000000002a060 T parseScalaLine(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
...
```

I traced that behaviour down to the libtool -export-symbols-regex feature used in src/Makefile.am:

```
amsynth_lv2_la_LDFLAGS = -rpath $(amsynth_lv2dir) -avoid-version -module -export-symbols-regex "lv2_descriptor" -disable-static
```

As far as I understand the situation, libtool will not successfully eliminate the symbols defined by C++. One possible solution could be using gcc's visibility feature, using -fvisibility=hidden to avoid exporting any symbols by default, and adding a visibility attribute to only the symbols you want to export.

**Comment by nickdowell** [comment]
Thanks for reporting this. Is it actually a problem?

If I use `nm`'s  `-g` option to show the exported symbols, I only see one:
```
nm -g amsynth_lv2.so
000000000003f124 T lv2_descriptor
```

**Comment by swesterfeld** [comment]
As far as I know, if the host would link against another shared library libfoo which exports a parameter_get_display function, then if the host loads the amsynth lv2 using  dlopen, the function from libfoo would also be used for amsynth, instead of the version amsynth provides, which would cause problems.

This is similar to the crashes you get if you try loading a plugin which uses Qt5 into a host using Qt4 (or the other way around).

I can't really comment on the exact difference beween nm -g versus -D, I only see that others are suggesting -D (in this case --dynamic) as well.
https://stackoverflow.com/questions/43256459/g-undefined-reference-although-symbol-is-present-in-so-file/43257338#43257338
