### ISSUE TITLE
3 enhancement suggestions

### ISSUE THREAD

**Issue by ZbigniewB** [amsynth/amsynth#129]
AmSynth is great - but three additional small features could make it even greater:

1. Adding "oscilloscope" window, which could be called from "Utils" menu. It could have great learning value to observe the final wave shape, its changes during tuning parameters etc. Of course no need to have such oscilloscope present all the time (as part of present GUI).
2. I think it would be handy to have ability to switch-off whole modules of synthesizer just by clicking their namefields (say: by clicking white letters "Reverb" one could switch reverb off completely with no need to change its parameters; the letters could then turn to gray or red to mark "inactive" state). Presently something like this I can see only in "Filter" module (I mean its "Bypass" menu option). Of course initially, after amsynth has been run, everything should be "on" by default.
3. Sub-oscillator would allow creation of even "thicker" sounds.

**Comment by ZbigniewB** [comment]
Fourth enhancement suggestion:
amSynth comes with rich library of sounds - thanks to Brian (whoever he is) - it's very interesting library of presets, but very easy way browsing it all could be done even easier.
Presently always when I pick any sound from the list, the list gets closed, and to select any other one I have to unwrap the whole menu again (and then again, and again, and again...). One little change would make browsing all these sounds more convenient: to make this list _not_ wrap immediately after any particular sound has been selected, and make it close only after I click that "down arrow" sign.
If feasible, also other way of selection could be added: single-click could apply selected preset without wrapping preset list, while double-click could mean "select and close list" (exactly like single-click does presently).

**Comment by trebmuh** [comment]
> thanks to Brian (whoever he is) 

(making a bet on) http://linuxsynths.com/

**Comment by nickdowell** [comment]
Thanks for the suggestions!

I have raised or linked individual issues for the points raised.
