### ISSUE TITLE
Incorrect Icon Location

### ISSUE THREAD

**Issue by Foggalong** [amsynth/amsynth#13]
The installer puts the icon in `@prefix@/share/pixmaps/amsynth.png` which breaks freedesktop guidelines. It should actually go in `/usr/share/icons/hicolor/` and then the icon line of the [.desktop file](https://github.com/amsynth/amsynth/blob/master/data/amsynth.desktop.in#L8) should just read `Icon=amsynth`. This allows theme developers to properly theme the icon and prevents breakage in style consistency.

**Comment by nixxcode** [comment]
Thanks for reporting this, had no idea!

Should be fixed by 68887a4 but let me know if not
