### ISSUE TITLE
Question - how could I control frequency directly rather than sending midi note number?

### ISSUE THREAD

**Issue by VinceLewis** [amsynth/amsynth#132]
So this is a question rather than a bug.

I still love amsynth and use it for all my synth needs. 
I am thinking I would like to do some software / hardware projects that would really benefit from being able to control the frequency of the note(s) directly rather than via the midi note number.

I am specifically thinking of something like a theremin device (which would be monophonic) and also a drone synth (which would ideally be polyphonic).

I was thinking this might be implemented by sending (say) three midi controller messages - the first to select the tone # and volume, and the next two to send the MSB and LSB of the frequency.

Two questions:
- How easy would this be to implement, in theory, in your software?
- Could you maybe point me at the relevant bits of code that accept the midi controller messages, and the bits that tell the oscillators which frequency to play?

Many thanks,
Vince

  - Which version of amsynth are you using?
1.5.1
  - Which build of amsynth are you using? (stand-alone application, LV2, DSSI, VST)
stand alone
  - If using amsynth as a plugin, which host application are you using?
  - Which operating system & version are you using?
Ubuntu 16.04.4 LTS

**Comment by nickdowell** [comment]
Hi!

This would be relatively easy (a few hours of work) to implement in amsynth.

I'm not aware of anything in the MIDI spec to handle this kind of input, so sysex or NRPNs might be appropriate. It would be worth doing some research to see if any existing MIDI controllers do anything similar (e.g. [MIDI Wind Controllers](https://en.wikipedia.org/wiki/Wind_controller))

`MidiController.cpp` contains all the MIDI note and controller message handling, and calls out via the `MidiEventHandler` interface to the `VoiceAllocationUnit`.

Functions would need to be added to the `MidiEventHandler` to handle volume and base pitch changes. The `VoiceAllocationUnit` could then update the voice by calling `VoiceBoard::setFrequency`

**Comment by VinceLewis** [comment]
Thank you for your full, excellent and speedy reply. When I'm feeling brave
I'll have a go and give you feedback - I've not had to "make" anything on
Linux before as I usually code in python but I'll give it a bash.

Vince

**Comment by nickdowell** [comment]
Closing this issue but feel free to get in touch if you have more questions
