### ISSUE TITLE
Please follow the XDG Base Directory Specification

### ISSUE THREAD

**Issue by piegamesde** [amsynth/amsynth#134]
### Expected behavior
All user files this application creates should be either in `$XDG_CONFIG_HOME`, `$XDG_CACHE_HOME` or `$XDG_DATA_HOME`.

https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

### Actual behavior
Currently, there are files everywhere, namely `~/.amsynth`, `~/.amSynthrc`, `.amSynth.presets`.

### Information

  - `1.9.0-1`
  - Stand-alone
  - Arch Linux, latest

### Steps to reproduce the behavior

Install and run the application

**Comment by nickdowell** [comment]
Plan is to migrate directories / files as follows;

```
~/.amSynthrc               --> $XDG_CONFIG_HOME/amsynth/config
~/.amSynthControllersrc    --> $XDG_CONFIG_HOME/amsynth/controllers
~/.amsynth/banks/          --> $XDG_DATA_HOME/amsynth/banks/
~/.amSynth.presets         --> $XDG_DATA_HOME/amsynth/banks/default
```

**Comment by nickdowell** [comment]
This can now be previewed on the [`feature/xdg-compliance`](/amsynth/amsynth/tree/feature/xdg-compliance) branch
* 069816cb97eecf9a5bc4fc19a5a41d50ce010262
