### ISSUE TITLE
Translation issue

### ISSUE THREAD

**Issue by trebmuh** [amsynth/amsynth#136]
Hi,

I've compiled 1.9.0 and I can't get it running in French. The .mo file is installed in /usr/share/locale/fr/LC_MESSAGES/amsynth.mo and it looks (cat-ing it) that it contains the French translation.

Any idea?

**Comment by nickdowell** [comment]
This is a bug :disappointed:

About to push a fix!

**Comment by trebmuh** [comment]
I've rebuild 1.9.0 with adding your patch, and the GUI is back to French. Lovely!

Thank you very much @nickdowell .
