### ISSUE TITLE
Package 1.6.4 for Ubuntu and Debian

### ISSUE THREAD

**Issue by PanderMusubi** [amsynth/amsynth#14]
Please, (help) package 1.6.4 for Ubuntu and Debian. See also https://bugs.launchpad.net/ubuntu/+source/amsynth/+bug/1537727

I also noted that https://amsynth.github.io/ still lists 1.6.3 as latest release, so you might want to update that too.

**Comment by nixxcode** [comment]
You can install up-to-date Ubuntu packages from my PPA;
https://launchpad.net/~nick-nickdowell/+archive/ubuntu/amsynth-master-daily

Will update the website soon :)

**Comment by PanderMusubi** [comment]
Thanks, it works fine. I don't use jackd and on the command line I get these messages:

    Cannot connect to server socket err = No such file or directory
    Cannot connect to server request channel
    jack server is not running or cannot be started
    snd_pcm_mmap_begin error

And perhaps you can comment or even close https://bugs.launchpad.net/ubuntu/+source/amsynth/+bug/1100016 and https://bugs.launchpad.net/ubuntu/+source/amsynth/+bug/1395718

**Comment by trebmuh** [comment]
It looks like it's on its way @Debian : https://anonscm.debian.org/gitweb/?p=pkg-multimedia/amsynth.git

**Comment by daev3000** [comment]
It's in Debian unstable and testing branches now, as well as in Ubuntu Zesty.
