### ISSUE TITLE
Issues with VST version of AMSynth

### ISSUE THREAD

**Issue by sub26nico** [amsynth/amsynth#140]
I have some issues with VST version of AMSynth 1.9.0. I don't know if it's AMSynth or hosts issue but I report it here and to hosts devs.
AmSynth 1.9.0 package from LibraZiK distro (based on Debian Stretch).
 1) In Ardour 5.12, no presets are found, lv2 works fine, and there is no problem with VST version in Qtractor, I have access to presets.
To reproduce: Add a MIDI track with AMSynth VST, open the AMSynth plugin window and click on preset button (second from left at the top of the window). Nothing is there.
2) In Reaper, I can't load the plugin, it freezes the host. 
From a terminal : 
```
(reaper:9349): GLib-GObject-WARNING **: cannot register existing type 'GdkWindow'

(reaper:9349): GLib-GObject-CRITICAL **: g_param_spec_object: assertion 'g_type_is_a (object_type, G_TYPE_OBJECT)' failed

(reaper:9349): GLib-GObject-CRITICAL **: g_object_class_install_property: assertion 'G_IS_PARAM_SPEC (pspec)' failed

** (reaper:9349): WARNING **: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

(reaper:9349): GLib-GObject-WARNING **: cannot register existing type 'GdkScreen'

(reaper:9349): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed

(reaper:9349): Gdk-CRITICAL **: IA__gdk_screen_get_default_colormap: assertion 'GDK_IS_SCREEN (screen)' failed

(reaper:9349): Gdk-CRITICAL **: IA__gdk_colormap_get_visual: assertion 'GDK_IS_COLORMAP (colormap)' failed




```

**Comment by sub26nico** [comment]
I can load presets by right-clicking in the AMSynth UI, but Ardour's plugin window doesn't show presets. 
Not sure it's Ardour's fault, with other plugins it works. I ask Ardour's dev on IRC.

**Comment by nickdowell** [comment]
1. The VST build of amsynth does not (currently) expose presets through VST's mechanism, so this is expected behaviour. Support for this could be added without too much difficulty. Do most of the other VST plugins you use expose their presets this way?

2. Rebuilding Reaper's `libSwell.so` with GDK2 instead of GDK3 (as documented in its `readme-linux.txt`) slightly improves the situation, but there are still issues. These will need investigation. Ultimately GTK is a bad choice for implementing plug-in GUIs... +1 for https://github.com/amsynth/amsynth/issues/37#issuecomment-489408479

**Comment by sub26nico** [comment]
> The VST build of amsynth does not (currently) expose presets through VST's mechanism, so this is expected behaviour. Support for this could be added without too much difficulty. Do most of the other VST plugins you use expose their presets this  way?

> 

Not all, I've got only one (overtoneDSP PTC-2A) allowing this, and few ones having just one (Initialize) but except ZynAddSubFx, they're all proprietaries. If you can add this feature, it could be good but it's not critical, so no worries about it, it's easy to have presets with a simple right-click.

> Rebuilding Reaper's libSwell.so with GDK2 instead of GDK3 (as documented in its readme-linux.txt) slightly improves the situation, but there are still issues. These will need investigation. Ultimately GTK is a bad choice for implementing plug-in GUIs... +1 for #37  (comment)

> 

Thanks, but i don't think i gonna rebuild libswell, if I have to use AMSynth, i'll use lv2 in Ardour. I just reported it fyi, i guess it's a Reaper issue so i've reported too in Reaper's forum and gonna add your answer to it. If you can improve it from your side, it's good but i don't gonna ask you to manage other devs 's issue.
Thanks @nickdowell  for your answers, i closed here

**Comment by nickdowell** [comment]
FYI I've updated the VST version of amsynth to disable the GUI under REAPER - this allows the plugin to be loaded and used with REAPER's generic controls.
