### ISSUE TITLE
Translation instructions don't work

### ISSUE THREAD

**Issue by fpesari** [amsynth/amsynth#145]
The instructions in amsynth/po don't work, as running `make amsynth.pot` from that directory does nothing.

```
make: *** No rule to make target 'amsynth.pot'.  Stop.
```

**Comment by nickdowell** [comment]
Turns out you need to run `./autogen.sh` and `./configure` to create the `Makefile` in the `po` directory. I have updated the instructions. Thanks for the report! :+1:
