### ISSUE TITLE
Keyboard shortcuts for LV2 plug-in

### ISSUE THREAD

**Issue by somethis** [amsynth/amsynth#147]
Hi Team,
here is a question / suggestion regarding the LV2 plugin used with Ardour5:
The keyboard shortcut CTRL + r to randomize settings makes amsynth very powerful for on the fly productions.

It seems, though, that this shortcut is not implemented in the LV2 version (or is it)? That would be a great addition.

Also, another shortcut that would be helpful would allow to select the next or previous preset. One solution would be to allow select the dropdown and choose the next entry with arrow up or down while the plugin receives midi signals.
This would allow the user to scan the plugins much faster, considering there are 26 "Factory" ... and 2.432 "Brians Bank" plugins. Right now, the only way to change the preset appears to be a mousclick on the dropdown menu and selecting the next preset with a click.

Please let me know if there is a way to implement this feature in the LV2 version. I can't code but could help out documenting, making a video or testing.

Version Details:
LV2 plugin with Ardour5.12.0, Ubuntu 18.04.3 LTS

**Comment by nickdowell** [comment]
Good suggestions, thanks! 👍
