### ISSUE TITLE
Port to GTK3

### ISSUE THREAD

**Issue by hellocatfood** [amsynth/amsynth#153]
### Expected behavior
Attempting to load amsynth in Zrythm (https://www.zrythm.org/ ). It should load the plguin's GUI

### Actual behavior
It loads a generic GUI

![Screenshot from 2020-02-17 12-12-52](https://user-images.githubusercontent.com/151947/74654992-6f69ed00-5183-11ea-93c4-2f5a76333daf.png)

### Steps to reproduce the behavior

  1. Install Zrythm
  2. load a track with the amsynth plugin
  3. Click on the piano icon to load the GUI

I have spoken to the developer of Zrythm and they say that the problem exists because "you can't load gtk2 plugins in the same process as a gtk3 program"

**Comment by alex-tee** [comment]
hi, i'm developing zrythm. the general idea is that plugin UIs should not use GTK or QT because of this. it's greatly discouraged, at least for new plugins. but if you do port, please do not use GTK or QT. i suggest using pugl https://github.com/lv2/pugl with cairo or opengl/nanovg instead

**Comment by nickdowell** [comment]
Hello and thanks for taking the time to file a detailed issue.

I agree that GTK or QT should not be used for plug-in UIs. The landscape and advice was a little different when amsynth was created 🙃

There's an open issue concerning rewriting the UI - https://github.com/amsynth/amsynth/issues/37 - I'll update it with info from here but feel free to add your own comments there!

amsynth will definitely _not_ be ported to GTK3, as it's the wrong long-term solution and would break compatibility with [Ardour](https://ardour.org)
