### ISSUE TITLE
Connections with a plugin in Carla 

### ISSUE THREAD

**Issue by manucontrovento** [amsynth/amsynth#155]
### Expected behavior

When loading my Carla session, AMSynth should connect its audio outputs just to a ZAM reverb inputs, as I saved it. 

### Actual behavior

But It always connect also to main system outputs, in addiction to ZAM reverb inputs. I thought that the problem could be in AMSynth, since opening Carla session file, I find only the connection I expected

### Information

  - Which version of amsynth are you using? 1.8.0
  - Which build of amsynth are you using? stand-alone application
  - If using amsynth as a plugin, which host application are you using? Carla
  - Which operating system & version are you using? Ubuntu Studio 19.10

### Steps to reproduce the behavior

  1. Save a session containing AMSynth and a stereo plugin, I used ZAM reverb, with AMSynth outputs connected to just reverb inputs and reverb outputs connected to system main outs
  2. Close and re open Carla and AMSynth will be connected to main outs too

**Comment by nickdowell** [comment]
When using amsynth in conjunction with Carla, do you need to start amsynth before loading the Carla session or does Carla take care of launching amsynth (like jack session support)?

amsynth has always connected itself to the system main outs at startup as a convenience. There is a command line option to disable this;

```
amsynth --jack_autoconnect=false
```

If it would help, I could make this configurable in amsynth's config file to avoid the need for command line arguments each time.

**Comment by manucontrovento** [comment]
hi @nickdowell , thanks a lot, with command line option I got what I needed! since I'm starting amsynth before loading the Carla session. Thanks!
