### ISSUE TITLE
Fails to build on Alpine Linux (musl) if ALSA is enabled

### ISSUE THREAD

**Issue by markand** [amsynth/amsynth#156]
### Expected behavior

On Alpine we don't use symbol versioning, ALSA does for their deprecated interfaces and so I think this is the reason it fails to build.

FWIW, an Alpine contributor found a similar patch for the project madplay which has the same errors: https://git.busybox.net/buildroot/patch/?id=97b392b98468859ab2366995b6bee4140b38e388

I'm not confident enough with the ALSA API to develop a patch for that issue. I can still use the software as LV2 plugin though (if built with `--without-alsa`).

### Actual behavior

```
 CXXLD    amsynth
/usr/lib/gcc/x86_64-alpine-linux-musl/9.2.0/../../../../x86_64-alpine-linux-musl/bin/ld: src/drivers/amsynth-ALSAmmapAudioDriver.o: in function `ALSAmmapAudioDriver::open()':
ALSAmmapAudioDriver.cpp:(.text+0x5c0): undefined reference to `snd_pcm_hw_params_set_rate_near@ALSA_0.9'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.2.0/../../../../x86_64-alpine-linux-musl/bin/ld: ALSAmmapAudioDriver.cpp:(.text+0x65d): undefined reference to `snd_pcm_hw_params_get_rate@ALSA_0.9'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:1898: amsynth] Error 1
make[2]: Leaving directory '/home/markand/downloads/amsynth-1.9.0'
make[1]: *** [Makefile:3619: all-recursive] Error 1
make[1]: Leaving directory '/home/markand/downloads/amsynth-1.9.0'
make: *** [Makefile:1459: all] Error 2
```

### Information

  - Which version of amsynth are you using? 1.9.0
  - Which operating system & version are you using? Alpine Linux

### Steps to reproduce the behavior

  1. `./configure --with-alsa`
  2. `make`

**Comment by nickdowell** [comment]
Thanks for the report, will look to fix in the upcoming release.

**Comment by nickdowell** [comment]
This should be fixed now, but I don't have a way to verify it - so please let me know!

**Comment by markand** [comment]
I can confirm that the latest Git commit builds fine, thanks for your work!

**Comment by nickdowell** [comment]
Great news, thanks! 💪
