### ISSUE TITLE
Allow saving presets in VST plugin

### ISSUE THREAD

**Issue by gnac** [amsynth/amsynth#158]
### Expected behavior
Dork with Synth Settings.
Click Save button on right side of Bank toolbar
Look in Presets to see 
### Actual behavior
No bank toolbar exists in VST version.
Right click context menu allows you to load presets, but there isn't any apparent way to save.

### Information

  - Which version of amsynth are you using? 1.9
  - Which build of amsynth are you using? (stand-alone application, LV2, DSSI, VST)
Stand-alone and VST.
  - If using amsynth as a plugin, which host application are you using?
Bitwig, and Carla Rack
  - Which operating system & version are you using?
Open Suse Linux 15.1
### Steps to reproduce the behavior

  1. Open the amsynth vst.
  2. look for a way to save preset settings.

This toolbar that exists in the standalone application doesn't exist in VST:
![image](https://user-images.githubusercontent.com/2447381/80896762-b2c5f900-8ca6-11ea-8398-4fa91d9c0320.png)
VST:
![image](https://user-images.githubusercontent.com/2447381/80896771-d25d2180-8ca6-11ea-8ea0-fd2c3e344512.png)

**Comment by nickdowell** [comment]
The plug-in version of amsynth currently doesn't offer a way to save presets. This is less of an issue for LV2 or Audio Units as presets can be normally be managed by the host application but the need for this functionality is acknowledged.

Blocked by #37
