### ISSUE TITLE
Feature Request: midi input controls

### ISSUE THREAD

**Issue by ftoledo** [amsynth/amsynth#16]
Please add support to control the "controls" via midi input.

**Comment by gethiox** [comment]
@ftoledo I think this feature is already implemented, just click right-mouse-button on selected controller and choose the source:

![03 03 2016-18 36 47 477919648](https://cloud.githubusercontent.com/assets/1618352/13503430/a6e3ebf6-e16f-11e5-8119-3399cb257dcf.png)

**Comment by nixxcode** [comment]
@gethiox is right :+1: 

Although, this feature is only available when running the amsynth as an application; the plug-in versions do not have full MIDI control...

**Comment by ftoledo** [comment]
Great! I was search and cannot  found howto do it.  Thanks for the info!
