### ISSUE TITLE
NSM not working in Arch Linux & KXStudio 1.10.0 packages

### ISSUE THREAD

**Issue by diovudau** [amsynth/amsynth#160]
### Expected behavior
Adding amsynth into an NSM session it should send the "announce" osc message etc.
The changelog states that NSM was added in 1.9 and it reportedly worked there.

### Actual behavior
Amsynth is treated like any other not-nsm program

### Information
  - Which version of amsynth are you using?
1.10

  - Which build of amsynth are you using? (stand-alone application, LV2, DSSI, VST)
Archlinux binary package standalone (JACK)

  - Which operating system & version are you using?
Archlinux

**Comment by Houston4444** [comment]
same thing on Ubuntu 18.04 + KxStudio Packages. version 1.10.0 too.

**Comment by nickdowell** [comment]
Hi @0mk 👋 as author of amsynth's NSM implementation, any chance you could help with this? 🙏

**Comment by 0mk** [comment]
I'll take a look at it.

**Comment by 0mk** [comment]
I have determined that the autotools-built version works as expected but the cmake-built version does not remember its session data. A work around for now would be to git clone and build from source using autotools. I.e. run autogen.sh, ./configure and make. I'll try to determine why the cmake build is broken.

**Comment by 0mk** [comment]
OK so someone made NSM code conditionally compiled but didn't add -DWITH_NSM to the list of compile options in CMakeLists.txt . That will fix the issue with the cmake build. I tested it locally and it works. Could you do me the honours Nick and make the change on my behalf as I am pretty busy for the rest of the day. Cheers.

**Comment by nickdowell** [comment]
Thanks @0mk !

**Comment by nickdowell** [comment]
Examining the [KXStudio amsynth pacakge](http://ppa.launchpad.net/kxstudio-debian/plugins/ubuntu/pool/main/a/amsynth/amsynth_1.10.0-1kxstudio3_amd64.deb) has revealed it was built without NSM support. I suspect the same is true for the Arch binary package.

Probably because amsynth's NSM support relies on the oscpack library, and if this is not present on the build machine the functionality will not be compiled in.

**Comment by nickdowell** [comment]
Reported to Arch Linux - https://bugs.archlinux.org/task/67184

**Comment by falkTX** [comment]
My bad, I thought amsynth would be using liblo like pretty much all others, but it is using oscpack instead.

Note that kxstudio packages are statically built, so you will never see liblo, sndfile or a few others with `ldd`

Now I am curious, was there a reason to pick oscpack vs liblo?

**Comment by 0mk** [comment]
Hi Filipe.

Sorry for the delayed response. I have been out all day enjoying the Sun! The oscpack library is used only for debug code, not for the session manager itself, which uses liblo directly. Oscpack is a c++ library that sits on top of liblo, adding extra functionality and making it cleaner and easier to code osc messages. When running apps under NSM, the apps have no access to a console for the display of debug messages, so I wrote a debug class that sends text messages out over osc. One may then run an osc application in a console window that receives these messages and can display them. Although the nsm code appears to be working properly at this time, I left the debug code in place in case there may be issues in future. There should be no issue with adding oscpack to kxstudio as it does not replace liblo but is just a layer on top of it as I have already said. I hope this answer addresses your question.

Cheers,  Martin.

**Comment by nickdowell** [comment]
To simplify packaging, the next amsynth release will not require oscpack for NSM support.

**Comment by nickdowell** [comment]
Look out for new 1.11.0 packages
