### ISSUE TITLE
How to submit patches?

### ISSUE THREAD

**Issue by pawa75** [amsynth/amsynth#161]
### Expected behavior
Some information on how to submit in the Online Documentation
### Actual behavior
No information exist now
### Information

  - Which version of amsynth are you using? 1.8.0 on Debian, newer version on Manjaro
  - Which build of amsynth are you using? (stand-alone application, LV2, DSSI, VST) Stans-alone and LV2
  - If using amsynth as a plugin, which host application are you using? Ardour
  - Which operating system & version are you using? Debian 10 and Manjaro

### Steps to reproduce the behavior

  1. I have made some patches, I don't now if you need more presets but I could submit these if you like? See following link https://drive.google.com/file/d/15TUWEvzMmEXN4XadIVRNKE8WIk_xFZhj/view?usp=sharing
  2. I clicked on the online documentation from the app and coud'nt find anything on submitting patches. Is submiting patches something that is asked for or unwanted?

**Comment by nickdowell** [comment]
Thanks for the contribution! I'll include your bank in the next release :+1:

**Comment by pawa75** [comment]
Hi,
Thanks, it feels great to contribute. Could you take the file from Brian's
website? I've fixed some names, sorting the sounds, fixed volumes etc.

And thanks for amsynth! It's sounds amazing!
/Patrik

Den tis 14 juli 2020 17:06Nick Dowell <notifications@github.com> skrev:

**Comment by pawa75** [comment]
Hi,
Here is another bank I've made if you want to include it as presets.

https://drive.google.com/file/d/1OFIRpJihpTBABYMe6HZ5N1Ro8ZwjPnUy/view?usp=drivesdk

/Patrik

Den tis 14 jul 2020 19:39P W <patfabwal@gmail.com> skrev:

**Comment by pawa75** [comment]
I'm very sorry. I noticed now that I made my sound using an older version of Amsynth. Some of them with ring modulation sound different on the recent version. I'll correct those sound and send the banks to Brian again.

**Comment by nickdowell** [comment]
Oh that sounds like a bug - banks created with an older version should not sound different in newer versions!

________________________________

**Comment by pawa75** [comment]
Hi, thanks for the answer.

It's seams as the balance between osc1 and 2 is switched on some
sounds with ring modulation active. I had a snare sound, with one osc
as noice and the other as square wave(I think). After I upgraded from
1.04 to 1.10, the snare sounded more like a square type of sound, than
noise like a snare. There were some other sounds that was affected
aswell but I could give you an another example if you want. But it's a
clearer sound on the recent version which is good.

Take care!

2020-08-07 18:49 GMT+02:00, Nick Dowell <notifications@github.com>:

**Comment by pawa75** [comment]
Hi,
I made some changes to the sounds and names.

Best regards
Patrik

**Comment by nickdowell** [comment]
I tracked down the bug with how ring mod sounds; it was [introduced in amsynth version 1.10.0](https://github.com/amsynth/amsynth/commit/e410c0c0a792d3ff5f1f5ab7ec4e71ca1bc39924#diff-0c43d42b4a5a6575a50a719654ab9f98L198) :grimacing:

**Comment by pawa75** [comment]
That's great. I'm glad that you found the bug. I've now changed some of the sound, but maybe they'll sound different after this is fixed. Should I use version version 1.8 as a reference or 1.10?

**Comment by nickdowell** [comment]
They will sound a bit different once the bug is fixed.

Since version 1.10.0 is buggy when it comes to the ring mod sound, I recommend using 1.8.0 or 1.9.0 as a reference instead.

I plan to release 1.11.0 that includes the fix in around 2 weeks.

**Comment by nickdowell** [comment]
1.11.0 was released a week ago - the ring mod sound should now be fixed :muscle: 

A [contributing guide](https://github.com/amsynth/amsynth/blob/develop/CONTRIBUTING.md) has been added to help future contributors.

**Comment by pawa75** [comment]
Thanks, the new guide is great. You could also include bank 2 and 3 of my
sounds from Brians site, if you want.

Den sön 27 sep. 2020 11:10Nick Dowell <notifications@github.com> skrev:

**Comment by pawa75** [comment]
Could you also update bank 1 with the next version of Amsynth? For sometime
ago I reworked the sounds and sent a new version of bank 1 to Brian. Could
you please download it from his site, if its not a big hassle?

Den sön 27 sep. 2020 11:16P W <patfabwal@gmail.com> skrev:

**Comment by pawa75** [comment]
Hi again.
You could update to those files if you want.

Best regards,
Patrik

2020-10-06 12:01 GMT+02:00, P W <patfabwal@gmail.com>:

**Comment by pawa75** [comment]
https://drive.google.com/drive/folders/17f_B0CSBcVxc0kaHv3om6jm088eDrifd?usp=sharing

**Comment by nickdowell** [comment]
Hi @pawa75 I notice that PatriksBank03 in your Google Drive link is not the same as the version on http://linuxsynths.com/amSynthdemos/amsynth.html - which one is the most recent / "correct" version?

**Comment by pawa75** [comment]
Hi,

Yes, I've update the file yesterday on my Google Drive.

We had a visit to my wife's parents last weekend. And one day later her
father got feber, and was later positively tested for covid.

We got also sick but its ok with us. It's was fun to make some new sounds
when I had'nt got the strenght to do something else :).

I don't know if you want a bank to be completed to be included? Or if you
want to include it anway? Now it's containing around 70 sounds, and I'm not
sure if I ever will complete it, maybe.

Thanks for asking. You could take the new version from my drive, it will
have the latest changes.

Take care.

Den sön 8 nov. 2020 07:27Nick Dowell <notifications@github.com> skrev:

**Comment by nickdowell** [comment]
Thank @pawa75 !

I'll stick to including full banks for now.

Wishing you and your family a full and swift recovery! 🤞

**Comment by pawa75** [comment]
Hi,
The third bank is ready with 128 sounds, and uploaded to my Google Drive.

Have a good weekend!

2020-11-08 12:12 GMT+01:00, Nick Dowell <notifications@github.com>:

**Comment by nickdowell** [comment]
> Hi, The third bank is ready with 128 sounds, and uploaded to my Google Drive.
>
> Have a good weekend!

Awesome, thanks! 😍

**Comment by pawa75** [comment]
Hi Nick,
It's still an inspiration for me to make sounds on Amsynth. I've one more bank finished if you want to include it.
https://drive.google.com/file/d/16R3ZkoPwLiEzEqj2663Huz8YwU1gAKl0/view?usp=sharing
Take care!
