### ISSUE TITLE
build breaks on autotols option to detect C++11

### ISSUE THREAD

**Issue by dvzrv** [amsynth/amsynth#169]
### Expected behavior
`./configure` step succeeds.

### Actual behavior
`./configure` fails:

```
./configure: line 11571: syntax error near unexpected token `noext,'
./configure: line 11571: `AX_CXX_COMPILE_STDCXX_11(noext, mandatory)'
```

Removing the `AX_CXX_COMPILE_STDCXX_11([noext], [mandatory])` in `configure.ac` fixes the issue: https://github.com/amsynth/amsynth/pull/163/files#r491717443

### Information

  - Which version of amsynth are you using? - 1.11.0
  - Which build of amsynth are you using? - happens during build
  - If using amsynth as a plugin, which host application are you using? - n/a
  - Which operating system & version are you using? Arch Linux

### Steps to reproduce the behavior

  1. Download and extract tarball for 1.11.0
  2. Run:
```
autoreconf -vfi
intltoolize -f
./configure --prefix=/usr
```

**Comment by nickdowell** [comment]
Hi @dvzrv thanks for reporting this.

`AX_CXX_COMPILE_STDCXX_11` is provided by the [GNU Autoconf Archive](https://www.gnu.org/software/autoconf-archive/Introduction.html#Introduction) so this needs to be installed in order to build the configure script. On Debian / Ubuntu the package is named `autoconf-archive`.

Note that this package is not normally required when building from the release tarball, as its `aclocal.m4` contains the macro. I'm curious, why are you running `autoreconf` and `intltoolize` with the tarball?

**Comment by dvzrv** [comment]
> `AX_CXX_COMPILE_STDCXX_11` is provided by the [GNU Autoconf Archive](https://www.gnu.org/software/autoconf-archive/Introduction.html#Introduction) so this needs to be installed in order to build the configure script. On Debian / Ubuntu the package is named `autoconf-archive`.

Thanks for the clarification! Pulling in that package during build time fixes this issue for me!

> Note that this package is not normally required when building from the release tarball, as its `aclocal.m4` contains the macro. I'm curious, why are you running `autoreconf` and `intltoolize` with the tarball?

I'm building from the auto-generated tarball, which does not have a pre-generated configure script.

**Comment by tank-trax** [comment]
github issues answers many a query

same issue
installing autoconf-archive resolved this issue however

```
  CXX      src/amsynth_lv2_la-amsynth_lv2.lo
src/amsynth_lv2.cpp:290:2: error: invalid conversion from ‘void* (*)(const _LV2_Descriptor*, double, const char*, const LV2_Feature* const*)’ to ‘void* (*)(const LV2_Descriptor*, double, const char*, const LV2_Feature* const*)’ [-fpermissive]
  &lv2_instantiate,
```

**Comment by dvzrv** [comment]
@tank-trax The error you describe is unrelated. Please open a new ticket
