### ISSUE TITLE
MIDI Learn

### ISSUE THREAD

**Issue by escutia** [amsynth/amsynth#17]
There is any way to save as default configuration the linked param (sustain, volume...) with MIDI CC? Or to do the "lean midi" option via terminal? My idea is when synth starts, all the knobs of my midi controller where linked without have to do it again manually. Thanks!

**Comment by nixxcode** [comment]
amsynth is supposed to save the MIDI controller assignments (if you change them away from default) in the file $HOME/.amSynthControllersrc

Does this not seem to be happening correctly?

It is possible to edit $HOME/.amSynthControllersrc with a text editor; each line corresponds to a MIDI CC and should either contain the name of a parameter as defined in https://github.com/amsynth/amsynth/blob/master/src/Preset.cc#L74 or "null" if the MIDI CC should not be mapped.

**Comment by escutia** [comment]
So, if in the line 8 it says "master_vol", this corresponds to a CC#7 midi message? If I write in the first 7 lines, it corresponds to CC#0, CC#1...CC#6? Thank you. I think I got it, I'm only having problems to find the "amSynthControllersrc" in raspbian.

**Comment by nixxcode** [comment]
That's right, line 1 sets the mapping for CC#0, line 2 is for CC#1 et cetera (there should be 128 lines in total)
