### ISSUE TITLE
MIDI channel setting does not work

### ISSUE THREAD

**Issue by rgbeitor** [amsynth/amsynth#170]
### Expected behavior
Every single instance receives and sends midi information only in its assigned channel.

### Actual behavior
Midi in acts as if "all channels" where configured in all instances (all instances sound at the same time, responding in any channel as if it were theirs). Midi out is sending all the relevant info in the same channel.
 
### Information
  - Which version of amsynth are you using?
1.10.0
  - Which build of amsynth are you using? (stand-alone application, LV2, DSSI, VST)
Stand-alone application.
  - If using amsynth as a plugin, which host application are you using?

  - Which operating system & version are you using?
Ubuntu 18.04.5 LTS \n \l
Linux cep 4.15.0-117-lowlatency #118-Ubuntu SMP PREEMPT Fri Sep 4 20:42:53 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### Steps to reproduce the behavior

For the midi in behaviour:
1. (I'm using claudia+cadence for the tests). Start studio.
2. Start two instances of amsynth, controlling the channel assigned. For example "amsynth -c 2 -n amsynth_1 --jack_autoconnect=false" and "amsynth -c 3 -n amsynth_2 --jack_autoconnect=false". Information in the gui is ok for those channel selections.
3. Connect in's and out's (midi + audio).
4. Send some notes/pc/cc to the synths.
5. At this point, it can work... or not.

For the midi out behaviour:
1. Repeat same steps to 3.
2. Connect a midi monitor to the two midi outs (jack_dump, kmidimon...).
3. Send some notes/pc/cc to the synths.
4. All out info is in the same channel. The behaviour is always the same.

Hello:
Thank you for this awesome piece of software.

I'm trying to include it in a portable synth project (soc based: rpi, opi) and I selected it because of its "substractive" simplicity, low resource consumption and the ability to send back information about changes in the controllers of the synth once they are mapped to a CC.

Right now, I'm programming a parser in python to allow the use of a control surface without jumps (even when a patch is changed in the gui or via midi), that fully relies in this feature.

Playing with several instances of the synth, let me detect this problem.

If you need more info or some tests (even compiling the software), please ask for it.

Thanks in advance.
Ramón

**Comment by nickdowell** [comment]
Thanks for the bug report, I will investigate as soon as I have time!

**Comment by rgbeitor** [comment]
Thanks in advance, Nick.
Again, if you need some more tests or whatever, please let me know.

**Comment by nickdowell** [comment]
This is now fixed in the `develop` branch

**Comment by rgbeitor** [comment]
Hello, Nick:

Thank you very much for the modifications.

I was compiling and testing the development 1.11 code. Here are the results. Testing conditions are the same as before: claudia/cadence with two synth instances; each one in a specific channel (2 and 3). The synths are launched by cli:

**Check one: MIDI in.**

- Straight test without modifications of parameters/channels/etc in the GUI. Each synth is responding in its own channel. WORKING.
- Same as before but testing midi learn. Seems to be also WORKING.
- CC's also operational for the selected channel. WORKING.
- Preselection of channels from cli. WORKING.

**Check two: MIDI out.**

- Whenever a control is moved in the GUI or a patch is applied, all MIDI messages sent by the synth (both instances) go to channel 1. **NOT WORKING**.

**Check three: GUI.**

- Changing channels in the GUI is not reliable. Sometimes it works, sometimes the instance keeps responding in the previous configured channel, in none, etc. **NOT WORKING**.

**Comment by nickdowell** [comment]
Thanks for testing the changes, sounds like I have a bit more debugging to do!

**Comment by rgbeitor** [comment]
YW
If you need specific tests, please request them.

Thanks again

**Comment by nickdowell** [comment]
Hi @rgbeitor there were several MIDI related bugs in there, please try the latest code from `develop` :pray:

**Comment by rgbeitor** [comment]
Hi again.

Everything seems to be working as it should. Congratulations and thanks again.

The tests themselves (same conditions as before):

**Straight from start.**

- Midi in

  Notes/CC working. Channel division. WORKING.

- Midi out

  Moving controllers in GUI. Messages sent in the right channel. WORKING.
  Changes in synth patch (GUI). Messages sent in the right channel. WORKING.
  Changes in synth patch (PC message sent in the right channel). Messages sent in the right channel. WORKING.
            
**Messing around with channels in GUI.**
- Midi in

  Changes of channels in GUI seems to be WORKING. Now you can use each instance as a voice, playing both at the same time (configuring it to use the same channel) or independently (different channels).

- Midi out

  Changes of channels in GUI seems to be WORKING. If a channel is changed in an specific instance (GUI), the Midi  messages are received and sent in the configured channel.

As additional note, version of the last development code is 1.11. Shouldn't it be 1.12? Nothing that really matters but for you to know.

Something that I also would like to ask is: Would it be too complex implementing support for relative encoders?

I hope I can end my python parser during the following weeks, but having direct support included in the synth would be great. Less software running in a small soc. By the way, amsynth would be probably the only softsynth with this kind of feature...

If it is something that sounds interesting to you, I'll do an "official" enhancement request. Of course I would try to help you with the different possible setups and testing.

As far as I know there are three different relative modes that mostly send two divergent values -63 and 65, for example.

In this case, 63 is like "add -1" to the referred controller and 65 is like "add +1". Acceleration of the knob is obtained with increments in 65 or decrements in 63. For example moving faster the knob to de right can give you a value of 68 that must be understood as "add +6".

This is what I'm doing (in python) to control those values:

...
 if message_CC_value < 53 and message_CC_value > 43: 
       check_save_send_rel_to_abs(message, -12)
			if message_CC_value < 63 and message_CC_value > 53:
				check_save_send_rel_to_abs(message, -6)
			if message_CC_value == 63:	#If 63, decrease by one.
				check_save_send_rel_to_abs(message, -1)
			if message_CC_value == 65:	#If 65, increase by one.
				check_save_send_rel_to_abs(message, 1)
			if message_CC_value  > 65 and message_CC_value < 75:
				check_save_send_rel_to_abs(message, 6)
			if message_CC_value > 75 and message_CC_value < 85:
				check_save_send_rel_to_abs(message, 12)
...

This is of course ok to my taste :) Sensitivity can be modified just changing those numbers.

I'll be doing more testing of the synth  in the coming days. If I find something, I'll let you know.
One more time, thanks!

Ramón

**Comment by nickdowell** [comment]
Thanks for testing the fix and confirming :+1: 

As for versioning, I normally wait until I know what changes will be in a release before setting the number. For example if there only bugfixes the next release will be 1.11.1, but if there are new features it will be 1.12.0

Support for relative encoders would be good to capture in a new issue. The information you've given already is useful, but for reference it would also help to have some example of hardware or software that also implement it.

**Comment by rgbeitor** [comment]
Hi, Nick.

Sorry about the delayed answer.

Yeah it is always nice to have something to work with. Let me take a look around. May be there is some kind of emulator. And if there isn't, I can try to revert my python to create delta CC's in the three different modes from some kind of controller. I need to investigate howto create a small gui to have a comfortable knob for you to play, but shouldn't be that complicated.

This days compiling, I was also taking a look to your code: nice! Of course outside of my current programming skills, but pretty nice.

Thanks again and BR
