### ISSUE TITLE
Version 1.12.1 error connecting Alsa Midi on Raspberry Pi OS (Raspberry Pi 4)

### ISSUE THREAD

**Issue by mrmanuke** [amsynth/amsynth#181]
### Expected behavior
With amsynth 1.12.1 running on Raspberry Pi OS, running aconnect -o to display midi outputs, amsynth appears in the list as "client 128". Amsynth can receive midi messages from external keyboards/other devices.

### Actual behavior
Amsynth does not appear in acconnect -o list when running version 1.12.1. Midi messages cannot be received.

### Information

  - Which version of amsynth are you using?
1.9.0 (alsa midi works correctly), 1.12.1 (alsa midi does not work, as described above)

### Steps to reproduce the behavior

  1. Follow "Build & Install from Git repository" instructions from wiki for newest Amsynth version, or download and build from source for older versions.
  2. Open Amsynth from command line or Raspberry OS gui
  3. Enter "aconnect -o" in command line

**Comment by nickdowell** [comment]
Thanks for the report!

This has been fixed in release 1.12.2

**Comment by mrmanuke** [comment]
It works! Thank you!
