### ISSUE TITLE
NSM implementation not according to the API

### ISSUE THREAD

**Issue by grammoboy2** [amsynth/amsynth#184]
NSM works, but it doesn't respect the API fully. It allows 'save as' for example
http://non.tuxfamily.org/nsm/API.html
https://linuxaudio.github.io/new-session-manager/api/index.html

For support: https://github.com/linuxaudio/new-session-manager

**Comment by falkTX** [comment]
save-as is fine, though should be renamed as "export as" to be more clear what it does.
the crucial part is that *it cannot change the filename used for the current session project*.
if that is the case, all is fine.

**Comment by nickdowell** [comment]
amsynth's "Save Bank As ..." feature _does_ change the filename used for the current session.

**Comment by falkTX** [comment]
Then please hide/disable that menu option if running under NSM. Or change the behaviour to be an export-only of sorts, that keeps the current session filename but allows an export.

**Comment by nickdowell** [comment]
I've made some adjustments in the `feature/nsm-compliance` branch that should disable the Save As menu when running with NSM.

Please let me know if it works for you, then I can merge the changes.

**Comment by diovudau** [comment]
Now it is correct behavior.

**Comment by falkTX** [comment]
Does "open bank" menu action change the current active preset that it will act upon save?

**Comment by nickdowell** [comment]
Yes "Open Bank" changes the current active bank, so I have now disabled that too.

The bank selection control on the main GUI is also probably not strictly NSM compliant since it changes the currently bank, but disabling that would severely limit amsynth's usability ¯\\_(ツ)_/¯

**Comment by diovudau** [comment]
I am not sure if I understand the bank change correctly, I am not an actual amsynth user.
NSM allows everything inside the session to change, no matter if by the user through or GUI or by loading an external (not in the session) file with additional settings or even binary data like samples.

What matters is that no saving outside the designated session path happens.

**Comment by nickdowell** [comment]
The bank selection UI allows quickly switching between the "installed" banks (those in `/usr/share/amsynth/banks` and `~/.local/share/amsynth/banks`).

However the NSM layer in amsynth maintains its own [`BankPath`](https://github.com/amsynth/amsynth/blob/develop/src/nsm/NsmHandler.h#L41) which appears to be unaffected by amsynth's File menu or bank selection control... If that is the case then the "Open Bank" and "Save Bank As ..." menu items don't actually need to be disabled after all.

I don't have NSM installed (ran out of time / patience trying to get it to build & install on Linux Mint) to verify this though, so need to rely on contributors 🙃 perhaps @0mk (the author of [amsynth's NSM support](https://github.com/amsynth/amsynth/pull/128)) can help clear this up? 🙏

**Comment by 0mk** [comment]
When running any application via the NSM Session Manager, the session manager is an application in its own right with its own window. The user will either create a new session  or select an existing session by clicking on a session name in the session manager window. A session consists of a number of applications, specified by the user when creating the session.  For each session created, the session manager will allocate a directory (folder) in which to save ALL the configuration data from every application for that session. If the user clicks on a pre-defined session (i.e. one that has previously been created and then saved and closed), the session manager will launch every application belonging to the session and tell each application where to fetch its saved session data from. It will pass a "Name" argument to the application which is an absolute file path consisting of the session directory followed by a unique name for the specific application instance. This Name argument is just a string which the application should treat as the location of either a file or a directory where it will retrieve and store its configuration data (eg banks and presets). In the case of amsynth, the Name argument is used to create a unique directory within the session directory. Amsynth then creates two files in that unique directory ; one for the bank data and one containing the preset number. Thus, each instance of amsynth within a session will store one set of bank data and a file containing the preset number. When the session is closed, the current bank and preset number are saved to the session  data and the amsynth instance is terminated. When the session is opened again, a new instance of amsynth will be created, which will load the saved bank data and select the saved preset. If a new bank or preset is selected via the amsynth gui, eg by using OpenBank, this will become the current bank or preset and when the session is closed (or saved) via the session manager gui, this new data will be saved as part of the session data. In this way, the user is free to change banks and presets at will and the new settings will be saved on closing or saving the session. If Save Bank As is used to save the bank data to some arbitrary location, then this will not have the effect of saving the session data. It will save a copy of the current bank to another location OUTSIDE of the session directory. This is not a problem but maybe Save Bank As could be renamed to something like Export Bank As to make it clearer that the operation does not save data to the session folder.

**Comment by nickdowell** [comment]
Thanks @0mk for the detailed explanation! That confirms my thinking that amsynth's  "Open Bank", "Save Bank As ..." and bank selection UI does not change where amsynth will save its NSM session data, so it  _is_ compliant with the NSM spec and no change is required.

Will close #185
