### ISSUE TITLE
RPI4 - cannot ./configure

### ISSUE THREAD

**Issue by phil123456** [amsynth/amsynth#189]
### Expected behavior

I want to build it

I did an ./autogen then ./configure

./configure: line 11739: syntax error near unexpected token `noext,'
./configure: line 11739: `AX_CXX_COMPILE_STDCXX_11(noext, mandatory)'

### Information

just cloned the last version of repo

cd amsynth/
sudo apt-get install autoconf autogen intltool
./autogen.sh 
./configure CFLAGS='-g -O0' 
autoreconf -if
./configure CFLAGS='-g -O0' 
./configure

still the same ssue

**Comment by nickdowell** [comment]
You need to `sudo apt install autoconf-archive` as described [in the Wiki](https://github.com/amsynth/amsynth/wiki/BuildingFromSource#build-dependencies)
