### ISSUE TITLE
New soundbank

### ISSUE THREAD

**Issue by pawa75** [amsynth/amsynth#197]
Hi Nick,
I have made one more soundbank for you to include, if you want to.

PatriksBank05
https://drive.google.com/file/d/1BGFUSxnfmqaOaeTNo3pl97JbJfVxjiS4/view?usp=sharing

Take care!

**Comment by nickdowell** [comment]
Thanks!

PatriksBank01 - 03 are currently in amsynth, is there also a PatriksBank04 that you'd like to share?

**Comment by pawa75** [comment]
Thanks for asking. It's here
https://drive.google.com/file/d/16R3ZkoPwLiEzEqj2663Huz8YwU1gAKl0/view?usp=drivesdk

Wish you and your family a Merry Christmas.

Den tors 23 dec. 2021 11:40Nick Dowell ***@***.***> skrev:

**Comment by pawa75** [comment]
Hi, I noticed that one preset was the same for bank4 and 5. So I made a new sound for bank 5. https://drive.google.com/file/d/1BGFUSxnfmqaOaeTNo3pl97JbJfVxjiS4/view?usp=sharing
