### ISSUE TITLE
Strange Amsynth Behaviour as a REAPER VSTi

### ISSUE THREAD

**Issue by reggiedrax** [amsynth/amsynth#205]
### Information

  - amsynth v1.12.4
  - Which build of amsynth are you using? VSTi (from KX)
  - REAPER v6.58
  - Linux Mint 5.4.0-113-lowlatency #127-Ubuntu SMP PREEMPT Wed May 18 15:12:18 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
System:    Kernel: 5.4.0-113-lowlatency x86_64 bits: 64 compiler: gcc v: 9.4.0 
           Desktop: Cinnamon 5.2.7 wm: muffin dm: LightDM Distro: Linux Mint 20.3 Una 
           base: Ubuntu 20.04 focal 
Machine:   Type: Laptop System: HP product: HP Pavilion Laptop 15-cw0xxx v: N/A serial: <filter> 
           Chassis: type: 10 serial: <filter> 
           Mobo: HP model: 84E7 v: 99.23 serial: <filter> UEFI: AMI v: F.42 date: 11/12/2019 
Battery:   ID-1: BAT0 charge: 3.7 Wh condition: 3.7/3.7 Wh (100%) volts: 12.9/11.6 
           model: Hewlett-Packard Primary serial: <filter> status: Full 
CPU:       Topology: Quad Core model: AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx bits: 64 
           type: MT MCP arch: Zen L2 cache: 2048 KiB 
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm bogomips: 31938 
           Speed: 1709 MHz min/max: 1600/2000 MHz Core speeds (MHz): 1: 1602 2: 1630 3: 1709 
           4: 1654 5: 1627 6: 1594 7: 1577 8: 1543 
Graphics:  Device-1: AMD Raven Ridge [Radeon Vega Series / Radeon Vega Mobile Series] 
           vendor: Hewlett-Packard driver: amdgpu v: 5.6.20.20.45 bus ID: 04:00.0 
           chip ID: 1002:15dd 
           Display: x11 server: X.Org 1.20.13 driver: amdgpu,ati unloaded: fbdev,modesetting,vesa 
           resolution: 1920x1080~60Hz, 3840x2160~60Hz 
           OpenGL: renderer: AMD RAVEN (DRM 3.40.0 5.4.0-113-lowlatency LLVM 10.0.1) 
           v: 4.6 Mesa 20.1.6 direct render: Yes 
Audio:     Device-1: AMD Raven/Raven2/Fenghuang HDMI/DP Audio vendor: Hewlett-Packard 
           driver: snd_hda_intel v: kernel bus ID: 04:00.1 chip ID: 1002:15de 
           Device-2: AMD Family 17h HD Audio vendor: Hewlett-Packard driver: snd_hda_intel 
           v: kernel bus ID: 04:00.6 chip ID: 1022:15e3 
           Device-3: BEHRINGER BCF2000 type: USB driver: snd-usb-audio bus ID: 1-2:10 
           chip ID: 1397:00bc 
           Device-4: BEHRINGER UMC404HD 192k type: USB driver: snd-usb-audio bus ID: 1-3:3 
           chip ID: 1397:0509 
           Sound Server: ALSA v: k5.4.0-113-lowlatency 
Network:   Device-1: Realtek RTL8821CE 802.11ac PCIe Wireless Network Adapter 
           vendor: Hewlett-Packard driver: rtl8821ce v: v5.5.2.1_35598.20191029 port: f000 
           bus ID: 02:00.0 chip ID: 10ec:c821 
           IF: wlo1 state: down mac: <filter> 
           Device-2: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet 
           vendor: Hewlett-Packard driver: r8169 v: kernel port: e000 bus ID: 03:00.0 
           chip ID: 10ec:8168 
           IF: eno1 state: up speed: 100 Mbps duplex: full mac: <filter> 
Drives:    Local Storage: total: 238.47 GiB used: 206.78 GiB (86.7%) 
           ID-1: /dev/nvme0n1 vendor: Toshiba model: N/A size: 238.47 GiB speed: 15.8 Gb/s 
           lanes: 2 serial: <filter> 
Partition: ID-1: / size: 232.28 GiB used: 206.77 GiB (89.0%) fs: ext4 dev: /dev/dm-0 
           ID-2: swap-1 size: 976.0 MiB used: 0 KiB (0.0%) fs: swap dev: /dev/dm-1 
Sensors:   System Temperatures: cpu: 68.2 C mobo: N/A gpu: amdgpu temp: 63 C 
           Fan Speeds (RPM): N/A 
Repos:     No active apt repos in: /etc/apt/sources.list 
           Active apt repos in: /etc/apt/sources.list.d/additional-repositories.list 
           1: deb [arch=amd64] https: //download.docker.com/linux/ubuntu bionic stable
           2: deb https: //debian.neo4j.com stable 4.1
           Active apt repos in: /etc/apt/sources.list.d/amdgpu-pro-local.list 
           1: deb [ trusted=yes ] file: /var/opt/amdgpu-pro-local/ ./
           Active apt repos in: /etc/apt/sources.list.d/damentz-liquorix-focal.list 
           1: deb http: //ppa.launchpad.net/damentz/liquorix/ubuntu focal main
           Active apt repos in: /etc/apt/sources.list.d/google-chrome.list 
           1: deb [arch=amd64] http: //dl.google.com/linux/chrome/deb/ stable main
           No active apt repos in: /etc/apt/sources.list.d/home:sfztools:sfizz.list 
           Active apt repos in: /etc/apt/sources.list.d/kxstudio-debian-ppas-2.list 
           1: deb http: //ppa.launchpad.net/kxstudio-debian/libs/ubuntu focal main
           2: deb http: //ppa.launchpad.net/kxstudio-debian/plugins/ubuntu focal main
           3: deb http: //ppa.launchpad.net/kxstudio-debian/apps/ubuntu focal main
           4: deb http: //ppa.launchpad.net/kxstudio-debian/kxstudio/ubuntu focal main
           Active apt repos in: /etc/apt/sources.list.d/kxstudio-debian-ppas.list 
           1: deb http: //ppa.launchpad.net/kxstudio-debian/libs/ubuntu bionic main
           2: deb http: //ppa.launchpad.net/kxstudio-debian/music/ubuntu bionic main
           3: deb http: //ppa.launchpad.net/kxstudio-debian/plugins/ubuntu bionic main
           4: deb http: //ppa.launchpad.net/kxstudio-debian/apps/ubuntu bionic main
           5: deb http: //ppa.launchpad.net/kxstudio-debian/kxstudio/ubuntu bionic main
           Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list 
           1: deb http: //packages.linuxmint.com una main upstream import backport
           2: deb http: //archive.ubuntu.com/ubuntu focal main restricted universe multiverse
           3: deb http: //archive.ubuntu.com/ubuntu focal-updates main restricted universe multiverse
           4: deb http: //archive.ubuntu.com/ubuntu focal-backports main restricted universe multiverse
           5: deb http: //security.ubuntu.com/ubuntu/ focal-security main restricted universe multiverse
           6: deb http: //archive.canonical.com/ubuntu/ focal partner
           Active apt repos in: /etc/apt/sources.list.d/windscribe-repo.list 
           1: deb https: //repo.windscribe.com/ubuntu bionic main
Info:      Processes: 380 Uptime: 1h 29m Memory: 14.63 GiB used: 6.17 GiB (42.2%) Init: systemd 
           v: 245 runlevel: 5 Compilers: gcc: 9.4.0 alt: 9 Client: Unknown python3.8 client 
           inxi: 3.0.38 

### Steps to reproduce the behaviour

  1. start REAPER
  2. Set amsynth to run in a separate process (otherwise the UI does not apear)
  3. Insert a track with amsynth as a VSTi, set MIDI input
  4. Play, moderately fast single notes for a couple of minutes, the sound amsynth produces changes.

I have recorded a session which reproduces the behaviour and looks at the MIDI event log - there appear to be only note events and nothing that should change amsyth settings that I can see.

Happy to provide MIDI files/event logs that reproduced the behaviour on my system - or anything else.

Some discussion here: [https://www.reddit.com/r/Reaper/comments/v5augn/amsyth_and_reaper_for_linux/?utm_source=share&utm_medium=web2x&context=3](url)

**Comment by nickdowell** [comment]
I have not been able to reproduce a problem with amsynth's sound changing on its own when testing with REAPER 6.59

Steps followed:
* `Insert virtual instrument on new track...`
* Right-click `VSTi: amsynth` and select `Separate process` before clicking `Add`
* Insert a MIDI item and add some notes to it
* Play with `[R]epeat` toggled to continually play notes for several minutes.
The sound did not change.

Is it possible that MIDI program change or controller messages are being sent to amsynth?

A minimal REAPER session that can reproduce the problem would be most helpful.

We might not be using the same version of the amsynth plugin - the downloads on https://kx.studio/Repositories:Plugins contain an old version (1.10.0) that is missing an important bugfix for MIDI handling in the VST plugin.

**Comment by reggiedrax** [comment]
Hello Nick,

[amsyth-test.RPP.zip](https://github.com/amsynth/amsynth/files/8848059/amsyth-test.RPP.zip)

Amsynth built and installed without issue - though I note that the LV2 version isn't visible from within REAPER.

Hi - here's a project that demonstrated the issue when I was recording it.

Amsynth stopped responding a few bars before the end. Once that had happened the plugin was silent and the UI would not reappear once I'd toggled it off. It does not respond again until REAPER has been restarted.

The project plays back without error, it's only when recording that there's a problem, making your plugin has developed good taste and is commenting on my playing...

Hope this is helpful, let me know what you need.

Reggie

**Comment by nickdowell** [comment]
Thanks for the test project, @reggiedrax!

Using it I was able to reproduce the issue (change in sound, dropped notes) when using the old (1.9.0) version of amsynth that's packaged with Linux Mint.

After switching to the latest version, however, the problem seems to be fixed :smiley:

If you've built amsynth from source, the VST will typically be installed into `/usr/local/lib/vst`, whereas packages (such as Linux Mint's) seem to install into e.g `/usr/lib/x86_64-linux-gnu/vst`. You may need to check / change REAPER's `VST plug-in paths` option to ensure it's loading the most recent version.

**Comment by reggiedrax** [comment]
Hi,

Thanks for checking this: I can no longer reproduce the issue of notes dropping and sound changing.

Annoyingly though, I can still reproduce the issue of amsynth not responding after an unpredictable (but > 2 mins) time when playing live using the vst.

I've checked for multiple version of the vst and I'm confident there's only the one version on my system now:

`sudo find / -name '*amsynth*so' 2>/dev/null`

returns:

`/home/john/Synths/amsynth-1.12.4/.libs/amsynth_vst.so`
`/usr/local/lib/vst/amsynth_vst.so`
`/timeshift/snapshots/2022-06-07_10-00-01/localhost/usr/local/lib/vst/amsynth_vst.so`

If you wan to pursue this I'm happy to repeat the tests with any debugging options amsynth may have or with a debugging version if it would be helpful. I'm not sure how much mileage there would be in that, it may be a nit-picky timing issue that could change with a debugging version of the vst.

**Comment by reggiedrax** [comment]
Hello Nick - sorry, I didn't check for your reply.

Yes, still a problem for me unfortunately.

**Comment by nickdowell** [comment]
I made some small changes to midi handling under vst that may have addressed the issue you're seeing - would you mind checking with the latest code on the develop branch?

If the problem is still there, it would be good to check if it only happens with certain presets / settings - that could indicate an issue in the signal path rather than midi handling.

**Comment by reggiedrax** [comment]
Will do, thx.

John

**Comment by reggiedrax** [comment]
Having a problem building the clone from the develop branch, I'm sure it's something obvious I've done wrong but I can't see it.

`git clone https://github.com/amsynth/amsynth.git`
`cd amsynth`
`./autogen.sh`
`./configure`

returns:
`checking how to hardcode library paths into programs... immediate`
`./configure: line 11745: syntax error near unexpected token 'noext,'`
`./configure: line 11745: 'AX_CXX_COMPILE_STDCXX_11(noext, mandatory)'`

and no makefile is generated

**Comment by nickdowell** [comment]
Thanks for trying - `sudo apt install autoconf-archive` should resolve the error related to `AX_CXX_COMPILE_STDCXX_11`

**Comment by reggiedrax** [comment]
Done - thank you. I'm a Python and Perl person usually so I didn't know where to go there. I'll test tomorrow and post an RPP if I can replicate the problem.

**Comment by reggiedrax** [comment]
Previously when playing live using the Derren 1 patch - so the patch loaded by default when the plugin is installed - for five minutes would reliably crash amsynth and could only be solved with a restart of reaper.

I played for about 30 mins, 15 of which were using the Derren 1 patch, without any issues.

So - not a rigorous test but I didn't have any problems at all.

I **_wasn't_** able to replicate the problem.

:)
