### ISSUE TITLE
Request: Display current Bank and Patch Name on plugin GUI

### ISSUE THREAD

**Issue by reggiedrax** [amsynth/amsynth#209]
An enhancement request.

### Expected behavior

I expected to be able to see which Bank and Patch are currently active displayed somewhere when using amsynth as a plugin.

### Actual behavior

I'm not able to see which Bank and Patch are currently active when using amsynth as a plugin. With so many Banks and Patches it's not possible (for me) to remember which of the Bank/Patch combinations I have used for that track - and it's easy to misclick (that's a real word) and load another by mistake, losing the Patch I was using.

### Information

- Which version of amsynth are you using? **Built from develop clone 21/6/22**
- Which build of amsynth are you using? (stand-alone application, LV2, DSSI, VST) **VST**
- If using amsynth as a plugin, which host application are you using? **REAPER v6.61**
- Which operating system & version are you using? **Linux Mint,**
`uname -a`
`Linux HP-Pavilion-Laptop-15-cw0xxx 5.13.0-51-lowlatency #58~20.04.1-Ubuntu SMP PREEMPT Tue Jun 14 12:26:40 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

### Steps to reproduce the behavior

1. Start REAPER
2. Insert track with amsynth VST

**Comment by nickdowell** [comment]
This feature has now been implemented on the `develop` (default) branch!

It's part of a bigger rewrite of the GUI (#37) and not quite ready for release yet but feedback is welcome if you're able to build the latest version from Git.

**Comment by reggiedrax** [comment]
Oh excellent, thx for the update Nick and I'll have a look.

John
