### ISSUE TITLE
Automatically send settings to midi_out

### ISSUE THREAD

**Issue by tomcombriat** [amsynth/amsynth#21]
Dear Nick,

I've been using amsynth for a while and first thank you for this very good software!
I saw recently that, at some point, amsynth was automatically sending its parameters through the midi_out port, but it does not seem to be the case on my version which I compiled from git.

Is this feature scheduled again? I found it very useful when changing from patterns to patterns without having a "jump" in the parameter when touching a knob.

I can help as far as I know of C++ if you want!

Cheers,

Tom

**Comment by nixxcode** [comment]
I have now implemented automatic output of MIDI CCs.
It currently works for the stand-alone version via ALSA and JACK.
The DSSI, LV2 and VST versions will not currently output MIDI.

**Comment by tomcombriat** [comment]
Brilliant!
Once my audio system is operational again I will test this and give some feedback.

Thanks for this improvement!
