### ISSUE TITLE
Switch from unmaintained lash library to the more active ladish one

### ISSUE THREAD

**Issue by GvMariani** [amsynth/amsynth#210]
The lash library, used for session management with jack sound server, is very old (last release in 2009) and unmaintained (no commit in the upstream git since July 2009).
Luckily there is a viable replacement: the Nedko Arnaudov's LADI Session Handler (https://github.com/LADI/ladish). It's a complete rewrite of lash and is much more active (last git commit was in February 2021); it's already used by Carla and Cadence packages from Kxstudio project. It also sports an handy compatibility layer (liblash): all it should be needed to use it is changing the references to lash and its headers in those for the ladish compatibility layer and its headers.

The test patch attached simply does this, without bothering to change "lash" in "ladish" in the messages: it builds and runs OK for simple use on my system...
[amsynth-1.12.4-use-ladish-for-lash.txt](https://github.com/amsynth/amsynth/files/8968508/amsynth-1.12.4-use-ladish-for-lash.txt)

Please consider  the switch...

### Information
  - Which version of amsynth are you using? 1.12.4
  - Which build of amsynth are you using? (stand-alone application, LV2, DSSI, VST) standalone application
  - If using amsynth as a plugin, which host application are you using?
  - Which operating system & version are you using? Rosa Linux (a Mandriva derivative) Fresh 2021.1 on x86_64

**Comment by nickdowell** [comment]
I think there is no need to change anything here.

If ladish is configured with `./waf configure --enable-liblash` then amsynth will build against it.

The supplied patch did not work for me... lash (ladish) was not detected because there is no `liblash.pc` installed by ladish; it installs `/usr/local/lib/pkgconfig/lash-1.0.pc`
