### ISSUE TITLE
Use midi sysex to set and get preset

### ISSUE THREAD

**Issue by apiel** [amsynth/amsynth#217]
Is there anyway to set a full preset to amsynth using midi?
Would be great to be able to either specify a file to load or even send the whole preset using midi sysex. Would be great to also be able to get the current preset settings by sending a midi sysex query.

**Comment by nickdowell** [comment]
amsynth doesn't support anything like that at the moment (it has no sysex capabilities)

**Comment by apiel** [comment]
thx for your answer

**Comment by nickdowell** [comment]
It sounds like a reasonable feature to have, so if someone is willing to raise a PR it would be welcome.

Would have to agree how to encode the presets into sysex - the on-disk format is spatially inefficient so unsuitable for transmission over MIDI's limited bandwidth.
