### ISSUE TITLE
Add support for MTS-ESP

### ISSUE THREAD

**Issue by nickdowell** [amsynth/amsynth#218]
https://github.com/ODDSound/MTS-ESP

There needs to be an option to disable MTS-ESP at build time because MTS-ESP is not really GPL compatible.

**Comment by tank-trax** [comment]
I totally encourage and am anxiously awaiting this enhancement

as an aside, the latest nightly builds of Surge XT can act as MTS-ESP Master, as well @baconpaul has corrected a memory leak issue in Linux when IPC is enabled

with this MTS-ESP Master feature implemented, any synth that has MTS-ESP Client support will get retuned by Surge XT if it is running and has an alternative tuning implemented with MTS-ESP Source enabled, and it will work whether or not Surge XT is in the session or running as a standalone application 

hoping to see this implemented soon

thanks

**Comment by nickdowell** [comment]
Support for MTS-ESP is now in! 🎉

To preview this feature, please check out and build the source code from Git or install from https://code.launchpad.net/~nick-nickdowell/+archive/ubuntu/amsynth-develop (note it could take up to 24 hours for a new build to appear there.)

**Comment by tank-trax** [comment]
will test this out soon
