### ISSUE TITLE
Question about headless mode

### ISSUE THREAD

**Issue by bgergely0** [amsynth/amsynth#219]
Is there a way to start amsynth in headless mode with a preset from a bank?

If not, what is the point of headless mode? How can I modify the settings in it?

**Comment by nickdowell** [comment]
Currently there's no option for specifying the preset number at start-up.

You can use MIDI program change (and bank change) messages to switch between presets and banks, though. In headless mode the expectation is that everything (parameters, preset selection) is driven by MIDI.

It would also be easy to add a preset number command line option; a pull request with that would be welcome.
