### ISSUE TITLE
amsynth LV2 crashes Ardour when closing plugin GUI

### ISSUE THREAD

**Issue by autostatic** [amsynth/amsynth#229]
### Expected behavior
After having opened the plugin GUI it can be closed again.

### Actual behavior
After having opened the plugin UI Ardour crashes (segmentation fault) when closing the plugin GUI.

### Information

  - Which version of amsynth are you using?
    1.13.2+935+e94c0f2+202312281333
  - Which build of amsynth are you using? (stand-alone application, LV2, DSSI, VST)
    LV2. VST version does not show this behaviour.
  - If using amsynth as a plugin, which host application are you using?
    Ardour 8.2
  - Which operating system & version are you using?
    Debian 12.4 Bookworm

### Steps to reproduce the behavior

  1. Open plugin GUI in Ardour
  2. Close it by either clicking on the x in the top right of the GUI or by clicking on the plugin in the channel strip again

Older versions of amsynth (i.e. 1.10.0) did not show this behaviour.

**Comment by autostatic** [comment]
Weird thing is that if you have multiple GUI's open you can close them without issues until you close the last one, then Ardour crashes nonetheless.

**Comment by nickdowell** [comment]
Thanks for reporting this; I have not been able to replicate a crash using `amsynth_1.13.2+935+e94c0f2+202312281333~ubuntu22.04.1_amd64.deb` and `Ardour-8.2.0-x86_64` (on Linux Mint 21.1) so don't yet know what the problem might be.

Please could you try triggering the crash again while running Ardour from the command line to see if there are any useful log messages? Also `coredumpctl info` may contain some useful information.

**Comment by autostatic** [comment]
I think you can close this issue, with a clean session amsynth LV2 does not crash so the session I was working with that gave me crashes is probably corrupted somewhere. So not an amsynth issue.

**Comment by nickdowell** [comment]
Ok thanks for the update! 👍
