### ISSUE TITLE
amsynth not keeping up with midi events

### ISSUE THREAD

**Issue by bfields** [amsynth/amsynth#23]
I've been fooling with a midi controller and amsynth, and finding that amsynth often gets behind.  E.g., if I play a repeated triad at about 180bpm while simultaneously moving a fader, the rhythm goes ragged and amsynth will still continue trying to play notes for several seconds after I've stopped.  I can also reproduce the problem without touching any other controls if I just play a long fast glissando.

The one other soft synth I tried (bristol's b3 emulation) didn't see this problem, so I'm assuming it's an amsynth issue.

I'm on Fedora 24 with amsynth-1.6.4.1.fc24.  I'm inexperienced with linux music, but experienced with linux development, and happy to build newer versions from git, etc., if that would help debug.  I'm running amsynth on a new laptop (Lenovo T460s w/ Core i7-6600U CPU @ 2.60GHz).  Setup is all Fedora defaults, using qjackctl to set up jack, except that I had to bump some ulimits so that jack and amsynth could succesfully memlock and get realtime priority.

**Comment by bfields** [comment]
I've also now reproduced the same problem on amsynth built from latest git (5e9161b952157cd3127a6851ecf9f90f5671799e).

**Comment by nixxcode** [comment]
Confirmed; I can reproduce this when using ALSA for MIDI input to amsynth (JACK MIDI appears to be fine)

**Comment by nixxcode** [comment]
@bfields thanks for reporting this! please re-open if it's still not fixed for you

**Comment by bfields** [comment]
That fixes it for me.  Thanks1
