### ISSUE TITLE
midi CC in in value <> midi CC out value ?

### ISSUE THREAD

**Issue by thijz** [amsynth/amsynth#26]
hi Nick

i just made a very simple setup with a BCR2000 connected to AMsynth and vice versa (so i have midi feedback from AMsynth > BCR)

using a GMIDImonitor on the output of AMsynth and a second GMIDImonitor on the incoming midi from the BCR i noticed something strange : 

when the BCR sends a CC message of value X to AMsynth, AMsynth immediately sends out a CC message on the same controller id to the BCR, however the value that AMsynth sends out is always X-1

this doesnt seem to be an issue, but i was wondering if this is 'works as intended' ?

grtz
Thijs

btw : using AMsynth 1.6.4-1~748~ubuntu16.04.1 from your PPA 
btw2 : i was a bit surprised that 'amsynth -v' outputs 'amsynth git' iso a real version

**Comment by nixxcode** [comment]
That is definitely not as intended... well spotted :)

re btw2: that's as intended for the PPA as it is the latest bleeding edge, although I admit it would be nicer if it contained more useful information

**Comment by nixxcode** [comment]
The PPA builds now have the fix
