### ISSUE TITLE
allowing internationalisation

### ISSUE THREAD

**Issue by trebmuh** [amsynth/amsynth#28]
Hi @nixxcode and thank you for **amsynth** which is a really nice piece of software.

I've been playing with it and packaging it for my **LibraZiK** audio studio project which is basically a Debian-based audio studio project focused on French speaking people.

During this process, I sent you 2 PR that you already merged to master. Thanks. I just send a third one 2 minutes ago.

Now, I've been translating the whole GUI and CLI messages in French for my LibraZiK. I didn't find any easy way to do so, then I made a big patch against the sources. It works for my purpose, but it's not very portable/sustainable/... so, I'm wondering if you would consider to internationalise amsynth? Be sure that if you would do so, and would tell me you did so, you will quickly have a French .po file (or other system) commited to your github repo!

Sorry not proposing a PR for that, but it's over my knowledges unfortunately.

Once again, thanks for amsynth.
Olivier

**Comment by nixxcode** [comment]
Hi @trebmuh thanks for suggesting this, I have added gettext support to the GUI so amsynth can now accept .po files!

Please see https://github.com/amsynth/amsynth/blob/translations/po/fr.po - you should be able to transfer the translations you have in your patch so that they become part of amsynth proper :)

**Comment by trebmuh** [comment]
@nixxcode , thanks for allowing internationalisation ! I just committed the French translation : https://github.com/amsynth/amsynth/pull/30
When it's merged against the branch "Translation", I'll try a rebuild of this branch to check if everything is working properly.

**Comment by nixxcode** [comment]
Thanks for the translation @trebmuh :+1:

**Comment by trebmuh** [comment]
Thanks @nixxcode for the quick merge. And thanks for having had corrected my 3 mistakes.
