### ISSUE TITLE
protect controller from beeing overwritten by preset

### ISSUE THREAD

**Issue by georgkrause** [amsynth/amsynth#38]
i thought about the topic of #12. the problem is that sometimes a preset change overwrites a parameter which should stay at this value, in my case it is drive, adsr or the lfo, in #12 is the volume mentioned. but i guess for everyone there are other controller, because it depends on the usecase. so my idea was to do it as flexible as possible and i have two ideas:

* set for each controller a protection mode, which prevent it from beeing overwritten
* specify the controller which should not be changed in the preset.

what do you think @nixxcode?

**Comment by nixxcode** [comment]
So I thought the first option was preferable; allowing the user to specify that a control should not be changed when switching presets.

With this latest change you can right-click on a control and toggle the "Override Preset" menu item to make amsynth ignore that preset when switching presets.

Let me know whether you think this is a good solution!

![amsynth-override](https://cloud.githubusercontent.com/assets/61777/18809569/f5ff4408-8276-11e6-8d06-22779ae84233.png)

**Comment by georgkrause** [comment]
pretty nice, good work! thank you for that! its works as expected but for me as a non nativ english speaker the text is a little confusing. maybe something like "protect" and a little tooltip would be better? now i think the controller overrides the preset which is not exactly what happens... but i dont really know what is better :(

**Comment by nixxcode** [comment]
> for me as a non nativ english speaker the text is a little confusing. maybe something like "protect" and a little tooltip would be better?

I'm trying to think of clearer text but not sure "Protect" is the right word; maybe "Lock" or "Ignore Preset Value"

> now i think the controller overrides the preset which is not exactly what happens... but i dont really know what is better :(

@georgkrause Sorry I don't understand what you mean :confused:

**Comment by trebmuh** [comment]
I'd say "Lock" is much better.

**Comment by georgkrause** [comment]
@nixxcode i just tried to explain why this confuses me...
i think "Ignore Preset Value" is the best one, lock sounds like: you cant change this anymore... but "lock" would also be better than "override preset"
