### ISSUE TITLE
JACK MIDI UI/UX issues

### ISSUE THREAD

**Issue by simonvanderveldt** [amsynth/amsynth#40]
Would it be possible to add JACK MIDI as input?

From what I've seen from for example LMMS (see LMMS/lmms#2038) adding JACK MIDI when the application already supports JACK audio is a relatively small change.

**Comment by nixxcode** [comment]
amsynth already does support jack midi input :-)

If you start amsynth when jackd is running, it should automatically use jack and create some midi ports - although they won't be automatically connected to anything.

amsynth will also normally create some alsa midi ports and say "midi: alsa" on the gui which may be a little confusing, but it will accept midi from either (and jack midi has sample accurate rendering!)

**Comment by simonvanderveldt** [comment]
Ohw, that's nice :)

Now that you mentioned this I tried ALSA and it is actually working, as in I see a `midi_in` JACK MIDI port and it actually works for getting midi into amsynth:)

Unfortunately I do get a pop-up stating that the MIDI doesn't work, and in the UI there is nothing shown after `MIDI: ` in the top right.
So I guess there's something not 100% right, see screenshot below:
![image](https://cloud.githubusercontent.com/assets/204286/18760320/d84ddb26-8100-11e6-8476-f3f75acb27c2.png)

I started amsynth with `amsynth -a jack -m midi` for this, but starting it without these arguments gives the same result.
Also, I guess it makes sense to make it explicit that JACK MIDI can be/has been chosen by adding it to the `-m` option and showing it in the UI?

**Comment by nixxcode** [comment]
amsynth's ui now handles jack midi better; it will show if jack midi is being used and will no longer show an error message if alsa / oss midi could not be opened :smile: 

![screenshot from 2016-09-24 14-48-38](https://cloud.githubusercontent.com/assets/61777/18808890/503a6972-8266-11e6-92ca-83605bfb5348.png)

**Comment by simonvanderveldt** [comment]
@nixxcode forgot to feedback on this, sorry for the delay, but this has been working perfectly for me. No surprises GUI wise anymore :) Thanks!
