### ISSUE TITLE
Question:

### ISSUE THREAD

**Issue by georgkrause** [amsynth/amsynth#42]
in some sounds turning up the drive has nearly the same effect than turning off the filter (bypass). so i am wondering how the signal is routet through. can the drive bypass the filter?

**Comment by nixxcode** [comment]
The drive does not bypass the filter, I think what you are describing occurs because bypassing the filter increases the signal level going into the distortion (drive)

Here is a rough layout of the audio signal path:
```
OSC 1 ---|
         OSC MIXER ---> FILTER ---> ADSR ---> VOLUME ---> DRIVE ---> REVERB ---> LIMITER
OSC 2 ---| 
```

**Comment by georgkrause** [comment]
makes sense, thank you!
