### ISSUE TITLE
gettext infrastructure mismatch

### ISSUE THREAD

**Issue by trebmuh** [amsynth/amsynth#43]
Hi @nixxcode ,
trying to build this new 1.7.0 version, I'm in front of:

```
...
Making all in po
make[3]: Entering directory '/tmp/buildd/amsynth-1.7.0/po'
*** error: gettext infrastructure mismatch: using a Makefile.in.in from gettext version 0.18 but the autoconf macros are from gettext version 0.19
Makefile:193: recipe for target 'check-macro-version' failed
make[3]: *** [check-macro-version] Error 1
...
```

and then, the build fails.
Info is that I'm running a Debian Jessie up to date which use gettext 0.19.3-2.

I don't understand what's going on here. Any hint?

**Comment by nixxcode** [comment]
I don't understand either, this is the first amsynth release using gettext. I will have to investigate...

**Comment by trebmuh** [comment]
If that can help, please, note that I've been building on the same system/computer the git version from 2016 09 24 number https://github.com/amsynth/amsynth/commit/7d404004cca5e7850d036a5a5d1a9b681c827df3 which was building fine.

**Comment by trebmuh** [comment]
If that can help, please, note that I've been building on the same system/computer the git version from 2016 09 24 number https://github.com/amsynth/amsynth/commit/7d404004cca5e7850d036a5a5d1a9b681c827df3 which was building fine.

**Comment by trebmuh** [comment]
Just rebuild https://github.com/amsynth/amsynth/commit/d065cb371deb412d7266ebf67e55ed7294a20513 from 2016 09 26 and it went fine. I'll try to build a more recent one now.

**Comment by nixxcode** [comment]
I think the problem is introduced when preparing the tarball, building from git will work because the output of ./autogen.sh and friends are not included

**Comment by trebmuh** [comment]
...and you are right. I just made a build from a fresh git clone and everything went fine.
It's all good for me at this stage.

Let me know if you need someone to test in case of you making a 1.7.1 version to fix this issue.
Cheers.

**Comment by nixxcode** [comment]
Please could you try the attached file?

[amsynth-1.7.0.zip](https://github.com/amsynth/amsynth/files/504242/amsynth-1.7.0.zip)

I have changed `AM_GNU_GETTEXT_VERSION` to `AM_GNU_GETTEXT_REQUIRE_VERSION` which should ensure the latest version of gettext is included in the tarball

P.S. had to use a .zip because GitHub doesn't allow attaching .tar.* files

**Comment by trebmuh** [comment]
@nixxcode : trying to build, it looks to be lost in an endless loop:
```
  && CONFIG_FILES=po/Makefile.in CONFIG_HEADERS= CONFIG_LINKS= \
       /bin/bash ./config.status
config.status: creating po/Makefile.in
config.status: executing depfiles commands
config.status: executing libtool commands
config.status: executing po-directories commands
config.status: creating po/POTFILES
config.status: creating po/Makefile
cd .. \
  && CONFIG_FILES=po/Makefile.in CONFIG_HEADERS= CONFIG_LINKS= \
       /bin/bash ./config.status
config.status: creating po/Makefile.in
config.status: executing depfiles commands
config.status: executing libtool commands
config.status: executing po-directories commands
config.status: creating po/POTFILES
config.status: creating po/Makefile
cd .. \

```

**Comment by nixxcode** [comment]
This is getting confusing! 😕 

I set up a fresh VM with debian 8.6 to try and investigate; installed the build dependencies...
```
apt-get install libgtk2.0-dev libgtkmm-2.4-dev libjack-jackd2-dev libasound-dev \
    liblash-compat-dev dssi-dev liblo-dev libsndfile-dev autopoint intltool
```
And then successfully built using `./configure` `make` and `make install`

Could you share your `config.log` file?

**Comment by trebmuh** [comment]
It might be because I'm building a .deb within a debian chroot (pbuilder) and specifically the debian/rules which override the `./configure`, `make` and `make install` steps.
I'll try to check that on my side, so don't worry about it.
Thanks.

**Comment by nixxcode** [comment]
Feel free to re-open if there is something we can change in amsynth to improve this

**Comment by trebmuh** [comment]
I've been rebuilding 1.8 on a stretch up-to-date recently and the issue isn't there anymore. Don't know what happened but all is good now.
