### ISSUE TITLE
make "ignore preset value" persistent

### ISSUE THREAD

**Issue by georgkrause** [amsynth/amsynth#45]
At the moment i need to set it up on every start. It would be great if amsynth could save them and load them on new startup.

**Comment by nixxcode** [comment]
amsynth does save and load the "ignore preset value" configuration; it is stored via the `ignored_parameters` line in `~/.amSynthrc`

Possible reasons this may not be working:
- permissions problem with `~/.amSynthrc`
- multiple instances of amsynth are running and overwriting each other's config
- a bug in amsynth

**Comment by georgkrause** [comment]
okay, i checked it and now it worked. strange, i will look on this topic and tell you when i know when it happens if it happens again. thank you!
