### ISSUE TITLE
Command line/Automation Questions

### ISSUE THREAD

**Issue by VinceLewis** [amsynth/amsynth#47]
Hi,

I'm using Ubuntu Studio 16.04, amsynth 1.5.1.

I would like to be able to start multiple instances of amsynth from the command line, each using a different midi channel. So I can use instance 1 controlled by a midi keyboard, and the other instances controlled by qtraktor.

Is it possible to do so? and have them GUI less ?

**Comment by nixxcode** [comment]
Yes, this is possible using the `-c <channel>` argument to specify a MIDI channel and `-x` to disable the GUI

**Comment by VinceLewis** [comment]
Cool. Is there a list of command line arguments? I couldn't see one.

And thanks for speedy reply, much appreciated.

**Comment by nixxcode** [comment]
`amsynth -h` (or `man amsynth`) will print a summary of the command line arguments, although `-x` is missing from the documented list

**Comment by VinceLewis** [comment]
Perfect.

Many thanks, again
Vince
