### ISSUE TITLE
Issues using multiple instances and MIDI channels

### ISSUE THREAD

**Issue by jeff-blank** [amsynth/amsynth#59]
Using v1.7.0 in Linux (Fedora 24), if I run two instances of amsynth and set each to use a different MIDI channel, I frequently find that playing on both channels will cause either one channel's note(s) to not be played (as though the key-down event(s) were misssed) or will cause a note from one channel to be stuck on (as though the key-up event was missed). The source of both channels is the same device with the keyboard split. I usually play 2- or 3-note chords with one hand (channel) and a single-note melody or bass line with the other. I've used amidi to verify that all key events are received by ALSA, and I've used other synth software to verify that the problem is specific to amsynth.

At one point, it seemed like this was more of an issue with JACK audio output and much less of one with ALSA output, but since then, it seems to happen pretty regularly with ALSA output as well.

**Comment by nixxcode** [comment]
This should be fixed now!

Let me know if the problem still happens with the latest code...

**Comment by jeff-blank** [comment]
seems totally fixed, can't reproduce it at all now. thanks for the quick response and the great software!

**Comment by jeff-blank** [comment]
also fixed a weird issue I was having with the pitch-bend wheel. forgot about that till I looked at the commit diff. =)

**Comment by nixxcode** [comment]
Great, thanks for reporting back! =]
