### ISSUE TITLE
Compilation failed on Fedora 23

### ISSUE THREAD

**Issue by nobrakal** [amsynth/amsynth#6]
Hi, the new 1.6.0 failed to compile on my Fedora (and generate many ugly errors). I think it's due to a lib problem.
Nothing related to the new vst plugin (fail with --with-vst or not)

Here the full output: http://paste.fedoraproject.org/271966/43364011

Thank you

**Comment by nixxcode** [comment]
Hi, that paste does not appear to contain the error messages (stderr) - I can see that ConfigDialog failed to compile, but not why...

**Comment by nobrakal** [comment]
I'm an idiot,

Just dig a little. I find the problem, it's due to c++11.

The line: /usr/include/c++/5.1.1/bits/c++0x_warning.h:32:2: erreur: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.

So, juste add the option, and all work fine. Can you please add a mention in the README or INSTALL file ?

I'll update the fedora package soon :)

**Comment by nobrakal** [comment]
Hi, just few more info here: https://gist.github.com/nobrakal/85a6080c1c3febe52b54
Very long output of mock (utility to build in a fresh buildroot)

Problems is that the rpm won't compile, even with the std=c++11 arg... And can't find why

**Comment by nixxcode** [comment]
I found that after running `./configure CXXFLAGS='-std=c++0x'` the build succeeded on Fedora 23.

I'm not sure whether this is a problem with amsynth's autoconf setup, or with sigc++

**Comment by nobrakal** [comment]
Found the issue: https://lists.fedoraproject.org/pipermail/devel/2015-September/214907.html
The problem was due to a new version of gtkmm. Fixed for me :)

Please have a look on the "upstreameable way" to fix this!

Thank you for your help, amsynth 1.6 will be soon in fedora's stable repo

**Comment by nixxcode** [comment]
Thanks for investigating! It certainly did not seem like an issue with amsynth itself.

I'll see if I can do something in the short term to work around this, but I obviously don't want to require c++11 for compilation as amsynth doesn't need it.

In the long term, I want to move away from gtkmm, so this might be the catalyst.

**Comment by nobrakal** [comment]
Ok, thank you very much for your help!
Don't worry for me and fedora package, all works fine now :)

Just maybe add a notice in README.
