### ISSUE TITLE
Translatable pop-up menu entries

### ISSUE THREAD

**Issue by koernepr** [amsynth/amsynth#67]
It would be nice if the pop-up menu entries (oscillator waveforms etc.) could be translated, too.

Doing a quick test, I got the translation to work for the standalone application using `N_()` and a later `gettext()` call as described [here](https://developer.gnome.org/glib/stable/glib-I18N.html#N-:CAPS) and with `./configure --without-dssi` (otherwise the build would fail).

**Comment by nixxcode** [comment]
@koernepr the pop-up menu entries can now be translated 😄

**Comment by trebmuh** [comment]
Nice, thanks guys !

**Comment by trebmuh** [comment]
Nice, thanks guys !
@nixxcode : would you mind updating the po files then I can update de fr.po to 100%?

**Comment by nixxcode** [comment]
@trebmuh po files have been updated

**Comment by koernepr** [comment]
Thank you :smiley:

**Comment by trebmuh** [comment]
Thanks, French translation done and already merged, thanks @nixxcode

**Comment by nixxcode** [comment]
Thanks for the translations 😃
