### ISSUE TITLE
Amsynth with automation lets Ardour4 crash

### ISSUE THREAD

**Issue by tierball** [amsynth/amsynth#8]
I have a project stub with only Amsynth and an automation in it, where Ardour crashes, when it plays to the end of an automation near a note.

The error line Ardour gives out before it crashes is:

"
ardour-4.2.546: src/Synthesizer.cpp:188: void Synthesizer::process(unsigned int, std::vector<amsynth_midi_event_t>&, float*, float*, unsigned int): Zusicherung »frames_until_next_event < frames_left_in_buffer« nicht erfüllt.
"

But this only happens, if the automation is ending near the last note, I think. If it ends somewhere else or if I play a loop, it wont crash there, but if I change automation while playing, it crashes again.

I use a realtime kernel with Debian Jessie and the Mate-Desktop and I use KXStudio, so the software is up to date.

I have uploaded the little project stub on wikisend.com, so you may inspect the behavior yourself:

http://wikisend.com/download/827318/amsynthBreaksArdour.tar.xz

The link is only valid for 7 days, it says. Please let me know, if you could not download it till then, so I may upload it again there or somewhere else. GitHub wont take the file.

By the way, I think Amsynth is awesome. In combination with automation you can create all sorts of drum sounds or funny or eerie synth sounds. Its just perfect.

Richard

**Comment by nixxcode** [comment]
Thanks for sending this bug report and sample project, I have a fix ready :-)
