### ISSUE TITLE
amsynth.pot kept under version control but removed by make clean

### ISSUE THREAD

**Issue by koernepr** [amsynth/amsynth#82]
### Expected behavior
`$ make clean; git status` after building shows a clean git working tree
 
### Actual behavior
`$ make clean; git status` after building lists `po/amsynth.pot` as removed

### Information

Tested with c10a46a and earlier on Xubuntu 16.10 Live doing an in-source build.

### Steps to reproduce the behavior

  1. `$ ./autogen.sh &&./configure CFLAGS='-g -O0' && make -j2`
  2. `$ make clean`
  3. `$ git status`

### Comment

As far as I can tell, the file gets removed due to the `mostlyclean` rule in `po/Makefile.in.in` (symlink to `/usr/share/intltool/Makefile.in.in`); so far, I did not find a proper way to prevent this.

Looking at a few other projects, some put the .pot file under version control, others don't; the GNU gettext documentation [leaves it open](https://www.gnu.org/software/gettext/manual/html_node/Translations-under-Version-Control.html).

In case you decide to drop the file from version control, at least `po/README.md` needs to be adjusted.

**Comment by nixxcode** [comment]
I had initially added `amsynth.pot` to the repository to make it slightly easier for translators to create a new .po file, but after further consideration have decided to remove it.

It is easy to regenerate, and translators could also use one of the existing .po files as a starting point if preferred.
