### ISSUE TITLE
build fails

### ISSUE THREAD

**Issue by trebmuh** [amsynth/amsynth#85]
Hi,

I'm trying to build a debian package with pbuilder from current git master.

But it fails with:
```
... zip ...
| Build LV2 plugin...................................... : yes
| Build VST plugin...................................... : yes
|
| Use libsndfile for .wav output support................ : yes
|
| Generate man pages using pandoc....................... : no

configure complete. now type 'make' to build amsynth
and then, as root, 'make install' to install

make[1]: Leaving directory '/tmp/buildd/amsynth-1.7.1+20170509~gitff5cf50'
   dh_auto_build -O--parallel
make[1]: Entering directory '/tmp/buildd/amsynth-1.7.1+20170509~gitff5cf50'
Makefile:4023: *** missing separator (did you mean TAB instead of 8 spaces?).  Stop.
make[1]: Leaving directory '/tmp/buildd/amsynth-1.7.1+20170509~gitff5cf50'
dh_auto_build: make -j1 returned exit code 2
debian/rules:17: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2
E: Failed autobuilding of package
W: no hooks of type C found -- ignoring
I: unmounting /var/cache/pbuilder/result filesystem
I: unmounting dev/pts filesystem
I: unmounting run/shm filesystem
I: unmounting proc filesystem
I: cleaning the build env 
I: removing directory /var/cache/pbuilder/build//20619 and its subdirectories
```

The relevant info here looks to be:
`Makefile:4023: *** missing separator (did you mean TAB instead of 8 spaces?).  Stop.`

### Information

  - Which version of amsynth are you using?
GIT from today
  - Which operating system & version are you using?
debian jessie stable up to date

Any idea why?

**Comment by nixxcode** [comment]
I'm not sure what causes this error, but there should be some clues in the Makefile. It could be a missing dependency; `intltool` `pandoc` and `autopoint` are now required in order to build.

For reference you can see my [Debian packaging recipe](http://bazaar.launchpad.net/~nick-nickdowell/amsynth/packaging/files/head:/debian/)

**Comment by trebmuh** [comment]
Hi @nickdowell , I'm back to amsynth so I can update you on this.
I've been redoing my packaging (merging some of the stuff from your recipe) and it builds fine now. Thanks!

Closing now.
