### ISSUE TITLE
No audio on other channels

### ISSUE THREAD

**Issue by acajaja** [amsynth/amsynth#88]
### Expected behavior
To switch MIDI channel and still hear audio output.

### Actual behavior
Audio output stops when switching to any other MIDI channel except 1

### Information

  - Which version of amsynth are you using?
1.4.2
  - Which build of amsynth are you using? (stand-alone application, LV2, DSSI, VST)
Stand-alone
  - If using amsynth as a plugin, which host application are you using?
  - Which operating system & version are you using?
Raspbian Jessie - current version as of this post.

### Steps to reproduce the behavior

  1. Start Amsynth
  2. Set channel to 1 in the Config menu
  3. I am using ALSA (amidiplay) to play MIDI files into Amsynth
    - aplaymidi -p <amsynth IN MIDI port> path-to-file(s)
  4. You should be able to hear audio output
  5. Switch to another channel (not 1) in the Ansynth Config menu
  6. Observe audio output stops and can no longer hear it.

**Comment by nixxcode** [comment]
Is the MIDI data sent by aplaymidi all on channel 1?

The expected behaviour is that amsynth will only respond to MIDI messages that are on its MIDI channel.
