### ISSUE TITLE
Build problem with current master

### ISSUE THREAD

**Issue by ycollet** [amsynth/amsynth#98]
I compiled amsynth from master branch.

The configure command I use: 

./configure --with-lv2 --with-jack --without-dssi --without-vst --prefix=/opt/amsynth-devel

During compilation, I found the following error message:

make[2] : on quitte le répertoire « /home/collette/repositories/amsynth/man »                                                                                           
make[2] : on entre dans le répertoire « /home/collette/repositories/amsynth »                                                                                           
make[2]: ***  Aucune règle pour fabriquer la cible « data/dssi-amsynth-plugin.metainfo.xml.in », nécessaire pour « all-am ». Arrêt.                                     
make[2] : on quitte le répertoire « /home/collette/repositories/amsynth »                                                                                               
Makefile:3392 : la recette pour la cible « all-recursive » a échouée                                                                                                    
make[1]: *** [all-recursive] Erreur 1

**Comment by nixxcode** [comment]
I have also encountered this after running a `make clean` - it seems to delete the files mentioned in the error message

Try running `git checkout -- data` to restore the files from git and running `make` again

**Comment by ycollet** [comment]
Thanks, it worked:
```
$ git checkout --
$ git reset --hard --
```
